#!/bin/sh

if [ "$CHANDLER_HOME" = "" ]
then
    CHANDLER_HOME=`pwd`
fi

if [ -d $CHANDLER_HOME/Chandler -a -f $CHANDLER_HOME/release/bin/python ]
then
    echo "Using $CHANDLER_HOME/release/bin/python"
    echo ""
else
    echo "Error:  Please set CHANDLER_HOME environment variable to point"
    echo "        to the directory that contains the Chandler and release"
    echo "        subdirectories, then rerun RunPython"
    exit 1
fi

PYTHONPATH=$CHANDLER_HOME/Chandler PYTHONHOME=$CHANDLER_HOME/release LD_LIBRARY_PATH=$CHANDLER_HOME/release/lib:$CHANDLER_HOME/release/dbxml/lib:$CHANDLER_HOME/release/db/lib $CHANDLER_HOME/release/bin/python -O $*
