#!/usr/bin/python

# Nifty hack by RobinD to get Leopard to load our Info.plist
# instead of Pythons - basically Leopard hasn't a clue that
# we are spawning Chandler in the background.
# 
# The environ var settings here must mirror what's done in RunPython
# --bear

import sys, os

execdir = os.path.dirname(sys.argv[0])
executable = sys.executable 
resdir = os.path.join(os.path.dirname(execdir), "Resources")
mainprogram = os.path.join(resdir, "Chandler.py")

os.environ['CHANDLERHOME'] = resdir
os.environ['CHANDLERBIN'] = resdir
os.environ['PYTHONPATH'] = '%(resdir)s/debug/site-packages:%(resdir)s:%(resdir)s/parcels' % locals()
os.environ['DYLD_LIBRARY_PATH'] = '%(resdir)s/debug/lib:%(resdir)s/debug/db/lib:%(resdir)s/debug/icu/lib' % locals()
os.environ['LC_PATH'] = '%(resdir)s/debug/share/locale' % locals()

os.chdir(resdir)
sys.argv.insert(1, mainprogram)
os.execve(executable, sys.argv, os.environ)

