#!/bin/sh

if [ "$CHANDLERHOME" = "" ]
then
    CHANDLERHOME=`dirname $0`
fi

if [ "$CHANDLERBIN" = "" ]
then
    CHANDLERBIN=$CHANDLERHOME
fi

export LD_LIBRARY_PATH=$CHANDLERBIN/release/db/lib:$CHANDLERBIN/release/lib:$CHANDLERBIN/release/icu/lib
export PYTHONPATH=$CHANDLERHOME:$CHANDLERHOME/parcels
export PYTHONHOME=$CHANDLERBIN/release

cd $CHANDLERHOME

$CHANDLERBIN/release/bin/python -O Chandler.py $*
