#!/bin/sh

if [ "$CHANDLERHOME" = "" ]
then
    CHANDLERHOME=`dirname $0`
fi

if [ "$CHANDLERBIN" = "" ]
then
    CHANDLERBIN=$CHANDLERHOME
fi

export LD_LIBRARY_PATH=$CHANDLERBIN/debug/db/lib:$CHANDLERBIN/debug/lib:$CHANDLERBIN/debug/icu/lib
export PYTHONPATH=$CHANDLERHOME:$CHANDLERHOME/parcels
export PYTHONHOME=$CHANDLERBIN/debug

cd $CHANDLERHOME

$CHANDLERBIN/debug/bin/python_d Chandler.py $*
