import wx, osaf, application
def run():
    """
        Choose menu 'File > Accounts...' (0)
        Left Mouse Down in ACCOUNTS_LIST (2)
        Left Mouse Down in INCOMING_EMAIL_ADDRESS (5)
        Type u'demo1@osafoundatino\x08\x08on.org' (9)
        Left Mouse Down in INCOMING_FULL_NAME (91)
        Type u'Demo1' (96)
        Left Mouse Down in INCOMING_PASSWORD (111)
        Choose menu 'Edit > Paste' (116)
        Left Mouse Down in ACCOUNTS_LIST (119)
        Left Mouse Down in OUTGOING_EMAIL_ADDRESS (123)
        Type u'demo1@osafoundation.org' (127)
        Left Mouse Down in OUTGOING_FULL_NAME (197)
        Type u'Demo1' (202)
        Left Mouse Down in OUTGOING_PASSWORD (217)
        Choose menu 'Edit > Paste' (222)
        Left Mouse Down in __wxID_OK__ (225)
        Choose menu 'Item > New > New Message' (230)
        Left Mouse Down in EditMailToAEStaticControl (232)
        Type u'demo2@osafoundation.org' (236)
        Left Mouse Down in HeadlineBlockAEStaticControl (306)
        Left Mouse Down in HeadlineBlockAEEditControl (309)
        Left Mouse Double Click in HeadlineBlockAEEditControl (311)
        Type u'title' (316)
        Left Mouse Down in NotesBlock (330)
        Type u'body' (334)
        Left Mouse Down in ApplicationBar (345)
        Choose toolbar button 'Send' (347)
        Left Mouse Down in HeadlineBlockAEStaticControl (348)
        Left Mouse Down in HeadlineBlockAEEditControl (351)
        Left Mouse Down in HeadlineBlockAEEditControl (353)
        Type u'v' (356)
        Left Mouse Down in NotesBlock (358)
        Type u'v' (362)
        Left Mouse Down in EditMailToAEStaticControl (364)
        Left Mouse Down in EditMailToAEEditControl (367)
        Left Mouse Down in EditMailToAEEditControl (369)
        Left Mouse Down in EditMailToAEEditControl (371)
        Left Mouse Double Click in EditMailToAEEditControl (373)
    """

    wx.GetApp().RunRecordedScript ([
        (0, wx.CommandEvent, {'associatedBlock':'PrefsAccountsItem', 'eventType':wx.EVT_MENU, 'sentTo':u'MainViewRoot'}, {}),
        (1, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'ACCOUNTS_LIST'}, {}),
        (2, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ACCOUNTS_LIST'}, {'m_leftDown':True, 'm_x':115, 'm_y':20}),
        (3, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ACCOUNTS_LIST'}, {'m_x':115, 'm_y':20}),
        (4, wx.CommandEvent, {'eventType':wx.EVT_LISTBOX, 'sentTo':u'ACCOUNTS_LIST', 'selectedItem':1}, {}),
        (5, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_leftDown':True, 'm_x':27, 'm_y':3}),
        (6, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {}),
        (7, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'selectionRange': (0,0)}, {'m_x':27, 'm_y':3}),
        (8, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':-2, 'UnicodeKey':68}),
        (9, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'recordedFocusWindow':u'INCOMING_EMAIL_ADDRESS', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u''}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':33, 'm_y':-2, 'UnicodeKey':100}),
        (10, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':-2, 'UnicodeKey':68}),
        (11, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'd'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':33, 'm_y':-2, 'UnicodeKey':69}),
        (12, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'd'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':33, 'm_y':-2, 'UnicodeKey':101}),
        (13, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':33, 'm_y':-2, 'UnicodeKey':69}),
        (14, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'de'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':33, 'm_y':-2, 'UnicodeKey':77}),
        (15, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'de'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':33, 'm_y':-2, 'UnicodeKey':109}),
        (16, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':33, 'm_y':-2, 'UnicodeKey':77}),
        (17, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'dem'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (18, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'dem'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (19, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (20, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':-2, 'UnicodeKey':49}),
        (21, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':-2, 'UnicodeKey':49}),
        (22, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':-2, 'UnicodeKey':49}),
        (23, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':33, 'm_y':-2, 'UnicodeKey':16}),
        (24, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':50, 'm_keyCode':50, 'm_shiftDown':True, 'm_x':33, 'm_y':-2, 'UnicodeKey':50}),
        (25, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':64, 'm_keyCode':64, 'm_shiftDown':True, 'm_x':33, 'm_y':-2, 'UnicodeKey':64}),
        (26, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':50, 'm_keyCode':50, 'm_shiftDown':True, 'm_x':33, 'm_y':-2, 'UnicodeKey':50}),
        (27, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':33, 'm_y':-2, 'UnicodeKey':16}),
        (28, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (29, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (30, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (31, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@o'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':33, 'm_y':-2, 'UnicodeKey':83}),
        (32, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@o'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':33, 'm_y':-2, 'UnicodeKey':115}),
        (33, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':33, 'm_y':-2, 'UnicodeKey':83}),
        (34, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@os'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':-2, 'UnicodeKey':65}),
        (35, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@os'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':33, 'm_y':-2, 'UnicodeKey':97}),
        (36, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osa'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':33, 'm_y':-2, 'UnicodeKey':70}),
        (37, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osa'}, {'m_rawCode':102, 'm_keyCode':102, 'm_x':33, 'm_y':-2, 'UnicodeKey':102}),
        (38, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':-2, 'UnicodeKey':65}),
        (39, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osaf'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (40, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osaf'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (41, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':33, 'm_y':-2, 'UnicodeKey':70}),
        (42, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafo'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':33, 'm_y':-2, 'UnicodeKey':85}),
        (43, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafo'}, {'m_rawCode':117, 'm_keyCode':117, 'm_x':33, 'm_y':-2, 'UnicodeKey':117}),
        (44, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (45, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':33, 'm_y':-2, 'UnicodeKey':85}),
        (46, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafou'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (47, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafou'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':33, 'm_y':-2, 'UnicodeKey':110}),
        (48, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (49, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoun'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':-2, 'UnicodeKey':68}),
        (50, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoun'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':33, 'm_y':-2, 'UnicodeKey':100}),
        (51, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':-2, 'UnicodeKey':68}),
        (52, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafound'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':-2, 'UnicodeKey':65}),
        (53, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafound'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':33, 'm_y':-2, 'UnicodeKey':97}),
        (54, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafounda'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':33, 'm_y':-2, 'UnicodeKey':84}),
        (55, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafounda'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':33, 'm_y':-2, 'UnicodeKey':116}),
        (56, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':-2, 'UnicodeKey':65}),
        (57, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundat'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':33, 'm_y':-2, 'UnicodeKey':73}),
        (58, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundat'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':33, 'm_y':-2, 'UnicodeKey':105}),
        (59, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':33, 'm_y':-2, 'UnicodeKey':84}),
        (60, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (61, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':33, 'm_y':-2, 'UnicodeKey':110}),
        (62, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatin'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (63, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatin'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (64, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':33, 'm_y':-2, 'UnicodeKey':73}),
        (65, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (66, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (67, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatino'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (68, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatino'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (69, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (70, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatin'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (71, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatin'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (72, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':33, 'm_y':-2, 'UnicodeKey':8}),
        (73, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (74, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (75, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatio'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (76, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatio'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':33, 'm_y':-2, 'UnicodeKey':110}),
        (77, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (78, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':-2, 'UnicodeKey':78}),
        (79, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':33, 'm_y':-2, 'UnicodeKey':190}),
        (80, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation'}, {'m_rawCode':46, 'm_keyCode':46, 'm_x':33, 'm_y':-2, 'UnicodeKey':46}),
        (81, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':33, 'm_y':-2, 'UnicodeKey':190}),
        (82, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (83, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':-2, 'UnicodeKey':111}),
        (84, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':-2, 'UnicodeKey':79}),
        (85, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.o'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':33, 'm_y':-2, 'UnicodeKey':82}),
        (86, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.o'}, {'m_rawCode':114, 'm_keyCode':114, 'm_x':33, 'm_y':-2, 'UnicodeKey':114}),
        (87, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':33, 'm_y':-2, 'UnicodeKey':82}),
        (88, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.or'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':33, 'm_y':-2, 'UnicodeKey':71}),
        (89, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.or'}, {'m_rawCode':103, 'm_keyCode':103, 'm_x':33, 'm_y':-2, 'UnicodeKey':103}),
        (90, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_EMAIL_ADDRESS'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':33, 'm_y':-2, 'UnicodeKey':71}),
        (91, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'demo1@osafoundation.org'}, {'m_leftDown':True, 'm_x':49, 'm_y':7}),
        (92, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'INCOMING_FULL_NAME'}, {}),
        (93, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'INCOMING_FULL_NAME', 'selectionRange': (0,0)}, {'m_x':49, 'm_y':7}),
        (94, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u''}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':51, 'm_y':9, 'UnicodeKey':16}),
        (95, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_shiftDown':True, 'm_x':51, 'm_y':9, 'UnicodeKey':68}),
        (96, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_FULL_NAME', 'recordedFocusWindow':u'INCOMING_FULL_NAME', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_shiftDown':True, 'm_x':51, 'm_y':9, 'UnicodeKey':68}),
        (97, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':68, 'm_keyCode':68, 'm_shiftDown':True, 'm_x':51, 'm_y':9, 'UnicodeKey':68}),
        (98, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':51, 'm_y':9, 'UnicodeKey':16}),
        (99, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'D'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':51, 'm_y':9, 'UnicodeKey':69}),
        (100, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'D'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':51, 'm_y':9, 'UnicodeKey':101}),
        (101, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':51, 'm_y':9, 'UnicodeKey':69}),
        (102, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'De'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':51, 'm_y':9, 'UnicodeKey':77}),
        (103, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'De'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':51, 'm_y':9, 'UnicodeKey':109}),
        (104, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':51, 'm_y':9, 'UnicodeKey':77}),
        (105, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'Dem'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':51, 'm_y':9, 'UnicodeKey':79}),
        (106, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'Dem'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':51, 'm_y':9, 'UnicodeKey':111}),
        (107, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':51, 'm_y':9, 'UnicodeKey':79}),
        (108, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'Demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':51, 'm_y':9, 'UnicodeKey':49}),
        (109, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'INCOMING_FULL_NAME', 'lastWidgetValue':u'Demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':51, 'm_y':9, 'UnicodeKey':49}),
        (110, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_FULL_NAME'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':51, 'm_y':9, 'UnicodeKey':49}),
        (111, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'INCOMING_PASSWORD', 'lastWidgetValue':u'Demo1'}, {'m_leftDown':True, 'm_x':21, 'm_y':13}),
        (112, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'INCOMING_PASSWORD'}, {}),
        (113, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'INCOMING_PASSWORD', 'selectionRange': (0,0)}, {'m_x':21, 'm_y':13}),
        (114, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_PASSWORD', 'lastWidgetValue':u''}, {'m_rawCode':17, 'm_controlDown':True, 'm_keyCode':308, 'm_x':23, 'm_y':15, 'UnicodeKey':17}),
        (115, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'INCOMING_PASSWORD', 'lastWidgetValue':u''}, {'m_rawCode':86, 'm_controlDown':True, 'm_keyCode':86, 'm_x':23, 'm_y':15, 'UnicodeKey':86}),
        (116, wx.CommandEvent, {'clipboard':u'ad3leib5', 'associatedBlock':'PasteItem', 'eventType':wx.EVT_MENU, 'sentTo':u'INCOMING_PASSWORD', 'lastWidgetValue':u''}, {}),
        (117, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_PASSWORD'}, {'m_rawCode':86, 'm_controlDown':True, 'm_keyCode':86, 'm_x':23, 'm_y':15, 'UnicodeKey':86}),
        (118, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'INCOMING_PASSWORD'}, {'m_rawCode':17, 'm_keyCode':308, 'm_x':23, 'm_y':15, 'UnicodeKey':17}),
        (119, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ACCOUNTS_LIST', 'recordedFocusWindow':u'INCOMING_PASSWORD', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u'ad3leib5'}, {'m_leftDown':True, 'm_x':22, 'm_y':28}),
        (120, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'ACCOUNTS_LIST'}, {}),
        (121, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ACCOUNTS_LIST'}, {'m_x':22, 'm_y':28}),
        (122, wx.CommandEvent, {'eventType':wx.EVT_LISTBOX, 'sentTo':u'ACCOUNTS_LIST', 'selectedItem':2}, {}),
        (123, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'recordedFocusWindow':u'ACCOUNTS_LIST', 'recordedFocusWindowClass':wx._controls.ListBox}, {'m_leftDown':True, 'm_x':31, 'm_y':10}),
        (124, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {}),
        (125, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'selectionRange': (0,0)}, {'m_x':31, 'm_y':10}),
        (126, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':12, 'UnicodeKey':68}),
        (127, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'recordedFocusWindow':u'OUTGOING_EMAIL_ADDRESS', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u''}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':33, 'm_y':12, 'UnicodeKey':100}),
        (128, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':12, 'UnicodeKey':68}),
        (129, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'd'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':33, 'm_y':12, 'UnicodeKey':69}),
        (130, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'd'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':33, 'm_y':12, 'UnicodeKey':101}),
        (131, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':33, 'm_y':12, 'UnicodeKey':69}),
        (132, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'de'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':33, 'm_y':12, 'UnicodeKey':77}),
        (133, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'de'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':33, 'm_y':12, 'UnicodeKey':109}),
        (134, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':33, 'm_y':12, 'UnicodeKey':77}),
        (135, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'dem'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (136, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'dem'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':12, 'UnicodeKey':111}),
        (137, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (138, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':12, 'UnicodeKey':49}),
        (139, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':12, 'UnicodeKey':49}),
        (140, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':33, 'm_y':12, 'UnicodeKey':49}),
        (141, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':33, 'm_y':12, 'UnicodeKey':16}),
        (142, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':50, 'm_keyCode':50, 'm_shiftDown':True, 'm_x':33, 'm_y':12, 'UnicodeKey':50}),
        (143, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1'}, {'m_rawCode':64, 'm_keyCode':64, 'm_shiftDown':True, 'm_x':33, 'm_y':12, 'UnicodeKey':64}),
        (144, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':33, 'm_y':12, 'UnicodeKey':16}),
        (145, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':33, 'm_y':12, 'UnicodeKey':50}),
        (146, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (147, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':12, 'UnicodeKey':111}),
        (148, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@o'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':33, 'm_y':12, 'UnicodeKey':83}),
        (149, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@o'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':33, 'm_y':12, 'UnicodeKey':115}),
        (150, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (151, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':33, 'm_y':12, 'UnicodeKey':83}),
        (152, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@os'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':12, 'UnicodeKey':65}),
        (153, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@os'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':33, 'm_y':12, 'UnicodeKey':97}),
        (154, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':12, 'UnicodeKey':65}),
        (155, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osa'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':33, 'm_y':12, 'UnicodeKey':70}),
        (156, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osa'}, {'m_rawCode':102, 'm_keyCode':102, 'm_x':33, 'm_y':12, 'UnicodeKey':102}),
        (157, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osaf'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (158, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osaf'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':12, 'UnicodeKey':111}),
        (159, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':33, 'm_y':12, 'UnicodeKey':70}),
        (160, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafo'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':33, 'm_y':12, 'UnicodeKey':85}),
        (161, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafo'}, {'m_rawCode':117, 'm_keyCode':117, 'm_x':33, 'm_y':12, 'UnicodeKey':117}),
        (162, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (163, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':33, 'm_y':12, 'UnicodeKey':85}),
        (164, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafou'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':12, 'UnicodeKey':78}),
        (165, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafou'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':33, 'm_y':12, 'UnicodeKey':110}),
        (166, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':12, 'UnicodeKey':78}),
        (167, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoun'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':12, 'UnicodeKey':68}),
        (168, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoun'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':33, 'm_y':12, 'UnicodeKey':100}),
        (169, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':33, 'm_y':12, 'UnicodeKey':68}),
        (170, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafound'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':12, 'UnicodeKey':65}),
        (171, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafound'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':33, 'm_y':12, 'UnicodeKey':97}),
        (172, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafounda'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':33, 'm_y':12, 'UnicodeKey':84}),
        (173, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafounda'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':33, 'm_y':12, 'UnicodeKey':116}),
        (174, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':33, 'm_y':12, 'UnicodeKey':65}),
        (175, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundat'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':33, 'm_y':12, 'UnicodeKey':73}),
        (176, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundat'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':33, 'm_y':12, 'UnicodeKey':105}),
        (177, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':33, 'm_y':12, 'UnicodeKey':84}),
        (178, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (179, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundati'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':12, 'UnicodeKey':111}),
        (180, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatio'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':12, 'UnicodeKey':78}),
        (181, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundatio'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':33, 'm_y':12, 'UnicodeKey':110}),
        (182, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':33, 'm_y':12, 'UnicodeKey':73}),
        (183, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (184, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':33, 'm_y':12, 'UnicodeKey':78}),
        (185, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':33, 'm_y':12, 'UnicodeKey':190}),
        (186, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation'}, {'m_rawCode':46, 'm_keyCode':46, 'm_x':33, 'm_y':12, 'UnicodeKey':46}),
        (187, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':33, 'm_y':12, 'UnicodeKey':190}),
        (188, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (189, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':33, 'm_y':12, 'UnicodeKey':111}),
        (190, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.o'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':33, 'm_y':12, 'UnicodeKey':82}),
        (191, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.o'}, {'m_rawCode':114, 'm_keyCode':114, 'm_x':33, 'm_y':12, 'UnicodeKey':114}),
        (192, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':33, 'm_y':12, 'UnicodeKey':79}),
        (193, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':33, 'm_y':12, 'UnicodeKey':82}),
        (194, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.or'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':33, 'm_y':12, 'UnicodeKey':71}),
        (195, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_EMAIL_ADDRESS', 'lastWidgetValue':u'demo1@osafoundation.or'}, {'m_rawCode':103, 'm_keyCode':103, 'm_x':33, 'm_y':12, 'UnicodeKey':103}),
        (196, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_EMAIL_ADDRESS'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':33, 'm_y':12, 'UnicodeKey':71}),
        (197, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'demo1@osafoundation.org'}, {'m_leftDown':True, 'm_x':39, 'm_y':7}),
        (198, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'OUTGOING_FULL_NAME'}, {}),
        (199, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'OUTGOING_FULL_NAME', 'selectionRange': (0,0)}, {'m_x':39, 'm_y':7}),
        (200, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u''}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':41, 'm_y':9, 'UnicodeKey':16}),
        (201, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_shiftDown':True, 'm_x':41, 'm_y':9, 'UnicodeKey':68}),
        (202, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_FULL_NAME', 'recordedFocusWindow':u'OUTGOING_FULL_NAME', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u''}, {'m_rawCode':68, 'm_keyCode':68, 'm_shiftDown':True, 'm_x':41, 'm_y':9, 'UnicodeKey':68}),
        (203, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':41, 'm_y':9, 'UnicodeKey':16}),
        (204, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':41, 'm_y':9, 'UnicodeKey':68}),
        (205, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'D'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':41, 'm_y':9, 'UnicodeKey':69}),
        (206, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'D'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':41, 'm_y':9, 'UnicodeKey':101}),
        (207, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':41, 'm_y':9, 'UnicodeKey':69}),
        (208, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'De'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':41, 'm_y':9, 'UnicodeKey':77}),
        (209, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'De'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':41, 'm_y':9, 'UnicodeKey':109}),
        (210, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':41, 'm_y':9, 'UnicodeKey':77}),
        (211, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'Dem'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':41, 'm_y':9, 'UnicodeKey':79}),
        (212, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'Dem'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':41, 'm_y':9, 'UnicodeKey':111}),
        (213, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':41, 'm_y':9, 'UnicodeKey':79}),
        (214, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'Demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':41, 'm_y':9, 'UnicodeKey':49}),
        (215, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'OUTGOING_FULL_NAME', 'lastWidgetValue':u'Demo'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':41, 'm_y':9, 'UnicodeKey':49}),
        (216, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_FULL_NAME'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':41, 'm_y':9, 'UnicodeKey':49}),
        (217, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'OUTGOING_PASSWORD', 'lastWidgetValue':u'Demo1'}, {'m_leftDown':True, 'm_x':42, 'm_y':10}),
        (218, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'OUTGOING_PASSWORD'}, {}),
        (219, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'OUTGOING_PASSWORD', 'selectionRange': (0,0)}, {'m_x':42, 'm_y':10}),
        (220, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_PASSWORD', 'lastWidgetValue':u''}, {'m_rawCode':17, 'm_controlDown':True, 'm_keyCode':308, 'm_x':44, 'm_y':12, 'UnicodeKey':17}),
        (221, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'OUTGOING_PASSWORD', 'lastWidgetValue':u''}, {'m_rawCode':86, 'm_controlDown':True, 'm_keyCode':86, 'm_x':44, 'm_y':12, 'UnicodeKey':86}),
        (222, wx.CommandEvent, {'clipboard':u'ad3leib5', 'associatedBlock':'PasteItem', 'eventType':wx.EVT_MENU, 'sentTo':u'OUTGOING_PASSWORD', 'lastWidgetValue':u''}, {}),
        (223, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_PASSWORD'}, {'m_rawCode':86, 'm_controlDown':True, 'm_keyCode':86, 'm_x':44, 'm_y':12, 'UnicodeKey':86}),
        (224, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'OUTGOING_PASSWORD'}, {'m_rawCode':17, 'm_keyCode':308, 'm_x':44, 'm_y':12, 'UnicodeKey':17}),
        (225, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'__wxID_OK__', 'recordedFocusWindow':u'OUTGOING_PASSWORD', 'recordedFocusWindowClass':wx._controls.TextCtrl, 'lastWidgetValue':u'ad3leib5'}, {'m_leftDown':True, 'm_x':14, 'm_y':4}),
        (226, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':'__wxID_OK__'}, {}),
        (227, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__wxID_OK__'}, {'m_x':14, 'm_y':4}),
        (228, wx.CommandEvent, {'eventType':wx.EVT_BUTTON, 'sentTo':'__wxID_OK__', 'recordedFocusWindow':'__wxID_OK__', 'recordedFocusWindowClass':wx._controls.Button}, {}),
        (229, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (230, wx.CommandEvent, {'associatedBlock':'NewMessageItem', 'eventType':wx.EVT_MENU, 'sentTo':u'MainViewRoot'}, {}),
        (231, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (232, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'EditMailToAEStaticControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'Untitled'}, {'m_leftDown':True, 'm_x':56, 'm_y':10}),
        (233, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEStaticControl'}, {'m_x':56, 'm_y':10}),
        (234, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'EditMailToAEEditControl'}, {}),
        (235, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'Add addresses'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':56, 'm_y':10, 'UnicodeKey':68}),
        (236, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'recordedFocusWindow':u'EditMailToAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'Add addresses'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':56, 'm_y':10, 'UnicodeKey':100}),
        (237, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':56, 'm_y':10, 'UnicodeKey':68}),
        (238, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'd'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':56, 'm_y':10, 'UnicodeKey':69}),
        (239, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'd'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':56, 'm_y':10, 'UnicodeKey':101}),
        (240, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'de'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':56, 'm_y':10, 'UnicodeKey':77}),
        (241, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'de'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':56, 'm_y':10, 'UnicodeKey':109}),
        (242, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':56, 'm_y':10, 'UnicodeKey':69}),
        (243, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'dem'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (244, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'dem'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':56, 'm_y':10, 'UnicodeKey':111}),
        (245, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':56, 'm_y':10, 'UnicodeKey':77}),
        (246, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (247, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':56, 'm_y':10, 'UnicodeKey':50}),
        (248, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':56, 'm_y':10, 'UnicodeKey':50}),
        (249, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':56, 'm_y':10, 'UnicodeKey':50}),
        (250, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':56, 'm_y':10, 'UnicodeKey':16}),
        (251, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2'}, {'m_rawCode':50, 'm_keyCode':50, 'm_shiftDown':True, 'm_x':56, 'm_y':10, 'UnicodeKey':50}),
        (252, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2'}, {'m_rawCode':64, 'm_keyCode':64, 'm_shiftDown':True, 'm_x':56, 'm_y':10, 'UnicodeKey':64}),
        (253, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':56, 'm_y':10, 'UnicodeKey':16}),
        (254, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':56, 'm_y':10, 'UnicodeKey':50}),
        (255, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (256, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':56, 'm_y':10, 'UnicodeKey':111}),
        (257, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (258, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@o'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':56, 'm_y':10, 'UnicodeKey':83}),
        (259, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@o'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':56, 'm_y':10, 'UnicodeKey':115}),
        (260, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':56, 'm_y':10, 'UnicodeKey':83}),
        (261, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@os'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':56, 'm_y':10, 'UnicodeKey':65}),
        (262, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@os'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':56, 'm_y':10, 'UnicodeKey':97}),
        (263, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':56, 'm_y':10, 'UnicodeKey':65}),
        (264, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osa'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':56, 'm_y':10, 'UnicodeKey':70}),
        (265, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osa'}, {'m_rawCode':102, 'm_keyCode':102, 'm_x':56, 'm_y':10, 'UnicodeKey':102}),
        (266, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':70, 'm_keyCode':70, 'm_x':56, 'm_y':10, 'UnicodeKey':70}),
        (267, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osaf'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (268, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osaf'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':56, 'm_y':10, 'UnicodeKey':111}),
        (269, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (270, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafo'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':56, 'm_y':10, 'UnicodeKey':85}),
        (271, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafo'}, {'m_rawCode':117, 'm_keyCode':117, 'm_x':56, 'm_y':10, 'UnicodeKey':117}),
        (272, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':85, 'm_keyCode':85, 'm_x':56, 'm_y':10, 'UnicodeKey':85}),
        (273, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafou'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':56, 'm_y':10, 'UnicodeKey':78}),
        (274, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafou'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':56, 'm_y':10, 'UnicodeKey':110}),
        (275, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':56, 'm_y':10, 'UnicodeKey':78}),
        (276, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoun'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':56, 'm_y':10, 'UnicodeKey':68}),
        (277, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoun'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':56, 'm_y':10, 'UnicodeKey':100}),
        (278, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':56, 'm_y':10, 'UnicodeKey':68}),
        (279, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafound'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':56, 'm_y':10, 'UnicodeKey':65}),
        (280, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafound'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':56, 'm_y':10, 'UnicodeKey':97}),
        (281, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafounda'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':56, 'm_y':10, 'UnicodeKey':84}),
        (282, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafounda'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':56, 'm_y':10, 'UnicodeKey':116}),
        (283, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':56, 'm_y':10, 'UnicodeKey':65}),
        (284, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':56, 'm_y':10, 'UnicodeKey':84}),
        (285, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundat'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':56, 'm_y':10, 'UnicodeKey':73}),
        (286, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundat'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':56, 'm_y':10, 'UnicodeKey':105}),
        (287, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundati'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (288, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundati'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':56, 'm_y':10, 'UnicodeKey':111}),
        (289, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':56, 'm_y':10, 'UnicodeKey':73}),
        (290, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundatio'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':56, 'm_y':10, 'UnicodeKey':78}),
        (291, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundatio'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':56, 'm_y':10, 'UnicodeKey':110}),
        (292, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (293, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':56, 'm_y':10, 'UnicodeKey':78}),
        (294, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':56, 'm_y':10, 'UnicodeKey':190}),
        (295, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation'}, {'m_rawCode':46, 'm_keyCode':46, 'm_x':56, 'm_y':10, 'UnicodeKey':46}),
        (296, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':190, 'm_keyCode':46, 'm_x':56, 'm_y':10, 'UnicodeKey':190}),
        (297, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (298, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':56, 'm_y':10, 'UnicodeKey':111}),
        (299, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':56, 'm_y':10, 'UnicodeKey':79}),
        (300, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.o'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':56, 'm_y':10, 'UnicodeKey':82}),
        (301, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.o'}, {'m_rawCode':114, 'm_keyCode':114, 'm_x':56, 'm_y':10, 'UnicodeKey':114}),
        (302, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':56, 'm_y':10, 'UnicodeKey':82}),
        (303, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.or'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':56, 'm_y':10, 'UnicodeKey':71}),
        (304, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.or'}, {'m_rawCode':103, 'm_keyCode':103, 'm_x':56, 'm_y':10, 'UnicodeKey':103}),
        (305, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'EditMailToAEEditControl'}, {'m_rawCode':71, 'm_keyCode':71, 'm_x':56, 'm_y':10, 'UnicodeKey':71}),
        (306, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEStaticControl', 'lastWidgetValue':u'demo2@osafoundation.org'}, {'m_leftDown':True, 'm_x':44, 'm_y':9}),
        (307, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEStaticControl'}, {'m_x':44, 'm_y':9}),
        (308, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (309, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'Untitled'}, {'m_leftDown':True, 'm_x':38, 'm_y':10}),
        (310, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEEditControl', 'selectionRange': (5,5)}, {'m_x':38, 'm_y':10}),
        (311, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_leftDown':True, 'm_x':38, 'm_y':10}),
        (312, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEEditControl', 'selectionRange': (0,8)}, {'m_x':38, 'm_y':10}),
        (313, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':40, 'm_y':12, 'UnicodeKey':16}),
        (314, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':40, 'm_y':12, 'UnicodeKey':16}),
        (315, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':40, 'm_y':12, 'UnicodeKey':84}),
        (316, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':40, 'm_y':12, 'UnicodeKey':116}),
        (317, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':40, 'm_y':12, 'UnicodeKey':84}),
        (318, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u't'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':40, 'm_y':12, 'UnicodeKey':73}),
        (319, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u't'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':40, 'm_y':12, 'UnicodeKey':105}),
        (320, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ti'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':40, 'm_y':12, 'UnicodeKey':84}),
        (321, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ti'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':40, 'm_y':12, 'UnicodeKey':116}),
        (322, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':40, 'm_y':12, 'UnicodeKey':73}),
        (323, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':40, 'm_y':12, 'UnicodeKey':84}),
        (324, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'tit'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':40, 'm_y':12, 'UnicodeKey':76}),
        (325, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'tit'}, {'m_rawCode':108, 'm_keyCode':108, 'm_x':40, 'm_y':12, 'UnicodeKey':108}),
        (326, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':40, 'm_y':12, 'UnicodeKey':76}),
        (327, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'titl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':40, 'm_y':12, 'UnicodeKey':69}),
        (328, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'titl'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':40, 'm_y':12, 'UnicodeKey':101}),
        (329, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':40, 'm_y':12, 'UnicodeKey':69}),
        (330, wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'title'}, {'m_leftDown':True, 'm_x':88, 'm_y':43}),
        (331, wx.FocusEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'NotesBlock'}, {}),
        (332, wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'NotesBlock', 'selectionRange': (0,0)}, {'m_x':88, 'm_y':49}),
        (333, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u''}, {'m_rawCode':66, 'm_keyCode':66, 'm_x':90, 'm_y':51, 'UnicodeKey':66}),
        (334, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':u'NotesBlock', 'recordedFocusWindow':u'NotesBlock', 'recordedFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u''}, {'m_rawCode':98, 'm_keyCode':98, 'm_x':90, 'm_y':51, 'UnicodeKey':98}),
        (335, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'b'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':90, 'm_y':51, 'UnicodeKey':79}),
        (336, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'b'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':90, 'm_y':51, 'UnicodeKey':111}),
        (337, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_UP, 'sentTo':u'NotesBlock'}, {'m_rawCode':66, 'm_keyCode':66, 'm_x':90, 'm_y':51, 'UnicodeKey':66}),
        (338, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'bo'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':90, 'm_y':51, 'UnicodeKey':68}),
        (339, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'bo'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':90, 'm_y':51, 'UnicodeKey':100}),
        (340, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_UP, 'sentTo':u'NotesBlock'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':90, 'm_y':51, 'UnicodeKey':79}),
        (341, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_UP, 'sentTo':u'NotesBlock'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':90, 'm_y':51, 'UnicodeKey':68}),
        (342, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'bod'}, {'m_rawCode':89, 'm_keyCode':89, 'm_x':90, 'm_y':51, 'UnicodeKey':89}),
        (343, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'bod'}, {'m_rawCode':121, 'm_keyCode':121, 'm_x':90, 'm_y':51, 'UnicodeKey':121}),
        (344, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_UP, 'sentTo':u'NotesBlock'}, {'m_rawCode':89, 'm_keyCode':89, 'm_x':90, 'm_y':51, 'UnicodeKey':89}),
        (345, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'lastWidgetValue':u'body'}, {'m_leftDown':True, 'm_x':480, 'm_y':32}),
        (346, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':480, 'm_y':32}),
        (347, wx.CommandEvent, {'associatedBlock':'ApplicationBarSendButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (348, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEStaticControl'}, {'m_leftDown':True, 'm_x':25, 'm_y':8}),
        (349, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEStaticControl'}, {'m_x':25, 'm_y':8}),
        (350, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (351, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'title'}, {'m_leftDown':True, 'm_x':23, 'm_y':6}),
        (352, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEEditControl', 'selectionRange': (4,4)}, {'m_x':23, 'm_y':6}),
        (353, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'title'}, {'m_leftDown':True, 'm_x':47, 'm_y':5}),
        (354, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEEditControl', 'selectionRange': (5,5)}, {'m_x':47, 'm_y':5}),
        (355, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'title'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':49, 'm_y':7, 'UnicodeKey':86}),
        (356, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'title'}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':49, 'm_y':7, 'UnicodeKey':118}),
        (357, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':49, 'm_y':7, 'UnicodeKey':86}),
        (358, wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'titlev'}, {'m_leftDown':True, 'm_x':90, 'm_y':73}),
        (359, wx.FocusEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'NotesBlock'}, {}),
        (360, wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'NotesBlock', 'selectionRange': (4,4)}, {'m_x':90, 'm_y':77}),
        (361, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'NotesBlock', 'lastWidgetValue':u'body'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':72, 'm_y':39, 'UnicodeKey':86}),
        (362, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':u'NotesBlock', 'recordedFocusWindow':u'NotesBlock', 'recordedFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u'body'}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':72, 'm_y':39, 'UnicodeKey':118}),
        (363, wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_UP, 'sentTo':u'NotesBlock'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':72, 'm_y':39, 'UnicodeKey':86}),
        (364, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'EditMailToAEStaticControl', 'lastWidgetValue':u'bodyv'}, {'m_leftDown':True, 'm_x':68, 'm_y':8}),
        (365, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEStaticControl'}, {'m_x':68, 'm_y':8}),
        (366, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'EditMailToAEEditControl'}, {}),
        (367, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'EditMailToAEEditControl', 'recordedFocusWindow':u'EditMailToAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'demo2@osafoundation.org'}, {'m_leftDown':True, 'm_x':66, 'm_y':6}),
        (368, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEEditControl', 'selectionRange': (10,10)}, {'m_x':66, 'm_y':6}),
        (369, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.org'}, {'m_leftDown':True, 'm_x':142, 'm_y':9}),
        (370, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEEditControl', 'selectionRange': (23,23)}, {'m_x':142, 'm_y':9}),
        (371, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.org'}, {'m_leftDown':True, 'm_x':23, 'm_y':12}),
        (372, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEEditControl', 'selectionRange': (3,3)}, {'m_x':23, 'm_y':12}),
        (373, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':u'EditMailToAEEditControl', 'lastWidgetValue':u'demo2@osafoundation.org'}, {'m_leftDown':True, 'm_x':23, 'm_y':12}),
        (374, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'EditMailToAEEditControl', 'selectionRange': (0,23)}, {'m_x':23, 'm_y':12}),
    ])
