import wx, osaf
from osaf.framework.script_recording.script_lib import ProcessEvent, VerifyOn

def run():
    VerifyOn ()
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'NewCollectionItem', 'eventType':wx.EVT_MENU, 'sentTo':'MainFrame'}, {})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':-309, 'newFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':139, 'm_y':-24, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':139, 'm_y':-24, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':139, 'm_y':-24, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':139, 'm_y':-24, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':139, 'm_y':-24, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':139, 'm_y':-24, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':139, 'm_y':-24, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':139, 'm_y':-24, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':16})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':78, 'm_keyCode':78, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':78})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':78, 'm_keyCode':78, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':78})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testN'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':139, 'm_y':-24, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testN'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':139, 'm_y':-24, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNe'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':139, 'm_y':-24, 'UnicodeKey':87})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNe'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':139, 'm_y':-24, 'UnicodeKey':119})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNew'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':16})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNew'}, {'m_rawCode':84, 'm_keyCode':84, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNew'}, {'m_rawCode':84, 'm_keyCode':84, 'm_shiftDown':True, 'm_x':139, 'm_y':-24, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewT'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':139, 'm_y':-24, 'UnicodeKey':65})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewT'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':139, 'm_y':-24, 'UnicodeKey':97})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewTa'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':139, 'm_y':-24, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewTa'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':139, 'm_y':-24, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewTas'}, {'m_rawCode':75, 'm_keyCode':75, 'm_x':139, 'm_y':-24, 'UnicodeKey':75})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewTas'}, {'m_rawCode':107, 'm_keyCode':107, 'm_x':139, 'm_y':-24, 'UnicodeKey':107})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testNewTask'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':139, 'm_y':-24, 'UnicodeKey':13})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'ApplicationBar', 'newFocusWindow':-219, 'newFocusWindowClass':wx.Window, 'lastWidgetValue':u'testNewTask'}, {'m_leftDown':True, 'm_x':124, 'm_y':37})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':'ApplicationBar'}, {'m_x':124, 'm_y':37})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'ApplicationBarTaskButton', 'eventType':wx.EVT_MENU, 'sentTo':'ApplicationBar'}, {})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'NewTaskItem', 'eventType':wx.EVT_MENU, 'sentTo':'MainFrame', 'newFocusWindow':-313, 'newFocusWindowClass':wx.Window}, {})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'newFocusWindow':-412, 'newFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':-387, 'm_y':-44, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':-387, 'm_y':-44, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-387, 'm_y':-44, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-387, 'm_y':-44, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':-387, 'm_y':-44, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':-387, 'm_y':-44, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':-387, 'm_y':-44, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':-387, 'm_y':-44, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test '}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':-387, 'm_y':-44, 'UnicodeKey':78})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test '}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':-387, 'm_y':-44, 'UnicodeKey':110})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test n'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-387, 'm_y':-44, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test n'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-387, 'm_y':-44, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test ne'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-387, 'm_y':-44, 'UnicodeKey':87})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test ne'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':-387, 'm_y':-44, 'UnicodeKey':119})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new '}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':-387, 'm_y':-44, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new '}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':-387, 'm_y':-44, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new t'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-387, 'm_y':-44, 'UnicodeKey':65})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new t'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-387, 'm_y':-44, 'UnicodeKey':97})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new ta'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':-387, 'm_y':-44, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new ta'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':-387, 'm_y':-44, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new tas'}, {'m_rawCode':75, 'm_keyCode':75, 'm_x':-387, 'm_y':-44, 'UnicodeKey':75})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new tas'}, {'m_rawCode':107, 'm_keyCode':107, 'm_x':-387, 'm_y':-44, 'UnicodeKey':107})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-387, 'm_y':-44, 'UnicodeKey':32})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task '}, {'m_rawCode':67, 'm_keyCode':67, 'm_x':-387, 'm_y':-44, 'UnicodeKey':67})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task '}, {'m_rawCode':99, 'm_keyCode':99, 'm_x':-387, 'm_y':-44, 'UnicodeKey':99})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task c'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':-387, 'm_y':-44, 'UnicodeKey':82})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task c'}, {'m_rawCode':114, 'm_keyCode':114, 'm_x':-387, 'm_y':-44, 'UnicodeKey':114})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task cr'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-387, 'm_y':-44, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task cr'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-387, 'm_y':-44, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task cre'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-387, 'm_y':-44, 'UnicodeKey':65})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task cre'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-387, 'm_y':-44, 'UnicodeKey':97})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task crea'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':-387, 'm_y':-44, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task crea'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':-387, 'm_y':-44, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creat'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-387, 'm_y':-44, 'UnicodeKey':73})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creat'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':-387, 'm_y':-44, 'UnicodeKey':105})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creati'}, {'m_rawCode':79, 'm_keyCode':79, 'm_x':-387, 'm_y':-44, 'UnicodeKey':79})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creati'}, {'m_rawCode':111, 'm_keyCode':111, 'm_x':-387, 'm_y':-44, 'UnicodeKey':111})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creatio'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':-387, 'm_y':-44, 'UnicodeKey':78})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'HeadlineBlock', 'lastWidgetValue':u'test new task creatio'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':-387, 'm_y':-44, 'UnicodeKey':110})
