import wx, osaf
from osaf.framework.script_recording.script_lib import ProcessEvent, VerifyOn

def run():
    VerifyOn ()
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'NewCollectionItem', 'eventType':wx.EVT_MENU, 'sentTo':'MainFrame'}, {})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':(osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl,-311)}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':65, 'm_keyCode':65, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':97, 'm_keyCode':97, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tea'}, {'m_rawCode':8, 'm_keyCode':8, 'm_rawFlags':917505, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':8, 'm_keyCode':8, 'm_rawFlags':917505, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_rawFlags':2031617, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':115, 'm_keyCode':115, 'm_rawFlags':2031617, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':65, 'm_shiftDown':True, 'm_keyCode':65, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':65, 'm_shiftDown':True, 'm_keyCode':65, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testA'}, {'m_rawCode':76, 'm_keyCode':76, 'm_rawFlags':2490369, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':108, 'm_keyCode':108, 'm_rawFlags':2490369, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_rawFlags':2490369, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':108, 'm_keyCode':108, 'm_rawFlags':2490369, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAll'}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAll'}, {'m_rawCode':68, 'm_shiftDown':True, 'm_keyCode':68, 'm_rawFlags':2097153, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':68, 'm_shiftDown':True, 'm_keyCode':68, 'm_rawFlags':2097153, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAllD'}, {'m_rawCode':65, 'm_keyCode':65, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':97, 'm_keyCode':97, 'm_rawFlags':1966081, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAllDa'}, {'m_rawCode':89, 'm_keyCode':89, 'm_rawFlags':1376257, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':121, 'm_keyCode':121, 'm_rawFlags':1376257, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'testAllDay'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':-129, 'm_x':136})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'ApplicationBarNewButton', 'eventType':wx.EVT_MENU, 'sentTo':'ApplicationBar', 'newFocusWindow':(wx.Window,-219), 'lastWidgetValue':u'testAllDay'}, {})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'EditAllDay', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'EditAllDay', 'newFocusWindow':(wx.Window,-307)}, {'m_x':1, 'm_leftDown':True, 'm_y':6})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'EditAllDay', 'eventType':wx.EVT_CHECKBOX, 'sentTo':'EditAllDay', 'newFocusWindow':'EditAllDay', 'lastWidgetValue':True}, {})
