import wx, osaf
from osaf.framework.script_recording.script_lib import ProcessEvent, VerifyOn

def run():
    VerifyOn ()
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'DashboardSummaryView'}, {'m_leftDown':True, 'm_x':299, 'm_y':27})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'DashboardSummaryView'}, {'m_x':299, 'm_y':27})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'DashboardSummaryView'}, {'m_leftDown':True, 'm_x':299, 'm_y':27})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__FocusWindow__', 'selectionRange': (0,34), 'newFocusWindow':-297, 'newFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl}, {'m_x':112, 'm_y':7})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Welcome to Chandler 0.7.dev-r14064'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':114, 'm_y':9, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Welcome to Chandler 0.7.dev-r14064'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':114, 'm_y':9, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':114, 'm_y':9, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':114, 'm_y':9, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':114, 'm_y':9, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':114, 'm_y':9, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':114, 'm_y':9, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':114, 'm_y':9, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':114, 'm_y':9, 'UnicodeKey':49})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':49, 'm_keyCode':49, 'm_x':114, 'm_y':9, 'UnicodeKey':49})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test1'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':114, 'm_y':9, 'UnicodeKey':13})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'Sidebar', 'newFocusWindow':-224, 'newFocusWindowClass':wx.Window, 'lastWidgetValue':u'test1'}, {'m_leftDown':True, 'm_x':101, 'm_y':114})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'Sidebar', 'newFocusWindow':-219, 'newFocusWindowClass':wx.Window}, {'m_x':101, 'm_y':114})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'Sidebar'}, {'m_leftDown':True, 'm_x':101, 'm_y':114})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'Sidebar', 'newFocusWindow':-308, 'newFocusWindowClass':wx.Window}, {'m_x':101, 'm_y':114})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':-312, 'newFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':79, 'm_y':39, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':79, 'm_y':39, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':79, 'm_y':39, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':79, 'm_y':39, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':79, 'm_y':39, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':79, 'm_y':39, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':79, 'm_y':39, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':79, 'm_y':39, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':79, 'm_y':39, 'UnicodeKey':50})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':79, 'm_y':39, 'UnicodeKey':50})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test2'}, {'m_rawCode':9, 'm_keyCode':9, 'm_x':79, 'm_y':39, 'UnicodeKey':9})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'TimedEvents', 'newFocusWindow':-219, 'newFocusWindowClass':wx.Window, 'lastWidgetValue':u'test2'}, {'m_leftDown':True, 'm_x':233, 'm_y':146})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'TimedEvents'}, {'m_x':233, 'm_y':146})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'TimedEvents', 'newFocusWindow':-308, 'newFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':233, 'm_y':146})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'TimedEvents'}, {'m_x':233, 'm_y':146})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'NewEventItem', 'eventType':wx.EVT_MENU, 'sentTo':'MainFrame', 'newFocusWindow':-309, 'newFocusWindowClass':osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor}, {})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':-308, 'newFocusWindowClass':wx.Window}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':186, 'm_y':511, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':186, 'm_y':511, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':-309, 'newFocusWindowClass':osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-2, 'm_y':-478, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-2, 'm_y':-478, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':-2, 'm_y':-478, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':-2, 'm_y':-478, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':-2, 'm_y':-478, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':-2, 'm_y':-478, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':-2, 'm_y':-478, 'UnicodeKey':50})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':50, 'm_keyCode':50, 'm_x':-2, 'm_y':-478, 'UnicodeKey':50})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u'test2'}, {'m_leftDown':True, 'm_x':134, 'm_y':43})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_LEFT_UP, 'sentTo':'NotesBlock', 'selectionRange': (0,0), 'newFocusWindow':'NotesBlock', 'newFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u''}, {'m_x':134, 'm_y':43})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u''}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':136, 'm_y':45, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':'NotesBlock', 'lastWidgetValue':u''}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':136, 'm_y':45, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':136, 'm_y':45, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':'NotesBlock', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':136, 'm_y':45, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':136, 'm_y':45, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':'NotesBlock', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':136, 'm_y':45, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':136, 'm_y':45, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':'NotesBlock', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':136, 'm_y':45, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_KEY_DOWN, 'sentTo':'NotesBlock', 'lastWidgetValue':u'test'}, {'m_rawCode':51, 'm_keyCode':51, 'm_x':136, 'm_y':45, 'UnicodeKey':51})
    ProcessEvent (wx.KeyEvent, {'associatedBlock':'NotesBlock', 'eventType':wx.EVT_CHAR, 'sentTo':'NotesBlock', 'lastWidgetValue':u'test'}, {'m_rawCode':51, 'm_keyCode':51, 'm_x':136, 'm_y':45, 'UnicodeKey':51})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'TimedEvents', 'lastWidgetValue':u'test3'}, {'m_leftDown':True, 'm_x':230, 'm_y':166})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'TimedEvents'}, {'m_x':230, 'm_y':166})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'TimedEvents', 'newFocusWindow':-308, 'newFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':230, 'm_y':166})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__FocusWindow__', 'selectionRange': (0,9), 'newFocusWindow':-309, 'newFocusWindowClass':osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor}, {'m_x':42, 'm_y':11})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':42, 'm_y':11, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':42, 'm_y':11, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':42, 'm_y':11, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':42, 'm_y':11, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':42, 'm_y':11, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':42, 'm_y':11, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':42, 'm_y':11, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':42, 'm_y':11, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':52, 'm_keyCode':52, 'm_x':42, 'm_y':11, 'UnicodeKey':52})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':52, 'm_keyCode':52, 'm_x':42, 'm_y':11, 'UnicodeKey':52})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test4'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':42, 'm_y':11, 'UnicodeKey':13})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test4'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':42, 'm_y':11, 'UnicodeKey':13})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'EditAllDay', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'EditAllDay', 'newFocusWindow':-308, 'newFocusWindowClass':wx.Window, 'lastWidgetValue':u''}, {'m_leftDown':True, 'm_x':7, 'm_y':12})
    ProcessEvent (wx.MouseEvent, {'associatedBlock':'EditAllDay', 'eventType':wx.EVT_LEFT_UP, 'sentTo':'EditAllDay', 'newFocusWindow':'EditAllDay', 'newFocusWindowClass':osaf.framework.attributeEditors.AttributeEditors.AECheckBox, 'lastWidgetValue':False}, {'m_x':7, 'm_y':12})
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'EditAllDay', 'eventType':wx.EVT_CHECKBOX, 'sentTo':'EditAllDay', 'lastWidgetValue':True}, {})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'AllDayEvents', 'lastWidgetValue':True}, {'m_leftDown':True, 'm_x':210, 'm_y':13})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'AllDayEvents'}, {'m_x':210, 'm_y':13})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'AllDayEvents', 'newFocusWindow':-306, 'newFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':210, 'm_y':13})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__FocusWindow__', 'selectionRange': (0,5), 'newFocusWindow':-305, 'newFocusWindowClass':osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor}, {'m_x':22, 'm_y':9})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test4'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':22, 'm_y':9, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test4'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':22, 'm_y':9, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':22, 'm_y':9, 'UnicodeKey':69})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u't'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':22, 'm_y':9, 'UnicodeKey':101})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':83, 'm_keyCode':83, 'm_x':22, 'm_y':9, 'UnicodeKey':83})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'te'}, {'m_rawCode':115, 'm_keyCode':115, 'm_x':22, 'm_y':9, 'UnicodeKey':115})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':84, 'm_keyCode':84, 'm_x':22, 'm_y':9, 'UnicodeKey':84})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'tes'}, {'m_rawCode':116, 'm_keyCode':116, 'm_x':22, 'm_y':9, 'UnicodeKey':116})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':53, 'm_keyCode':53, 'm_x':22, 'm_y':9, 'UnicodeKey':53})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test'}, {'m_rawCode':53, 'm_keyCode':53, 'm_x':22, 'm_y':9, 'UnicodeKey':53})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test5'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':22, 'm_y':9, 'UnicodeKey':13})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'test5'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':22, 'm_y':9, 'UnicodeKey':13})
