import wx, osaf
from osaf.framework.script_recording.script_lib import ProcessEvent, VerifyOn

def run():
    VerifyOn ()
    ProcessEvent (wx.CommandEvent, {'associatedBlock':'ApplicationBarNewButton', 'eventType':wx.EVT_MENU, 'sentTo':'ApplicationBar'}, {})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'DashboardSummaryView', 'newFocusWindow':(osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl,-253)}, {'m_x':215, 'm_leftDown':True, 'm_y':24})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'DashboardSummaryView', 'newFocusWindow':(wx.Window,-224)}, {'m_x':215, 'm_leftDown':True, 'm_y':24})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__FocusWindow__', 'selectionRange': (0,9), 'newFocusWindow':(osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl,-297)}, {'m_x':28, 'm_y':4})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':82, 'm_shiftDown':True, 'm_keyCode':82, 'm_rawFlags':1245185, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':82, 'm_shiftDown':True, 'm_keyCode':82, 'm_rawFlags':1245185, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'R'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Re'}, {'m_rawCode':78, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':110, 'm_keyCode':110, 'm_rawFlags':3211265, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Ren'}, {'m_rawCode':65, 'm_keyCode':65, 'm_rawFlags':1966081, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':97, 'm_keyCode':97, 'm_rawFlags':1966081, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Rena'}, {'m_rawCode':77, 'm_keyCode':77, 'm_rawFlags':3276801, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':109, 'm_keyCode':109, 'm_rawFlags':3276801, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renam'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Rename'}, {'m_rawCode':68, 'm_keyCode':68, 'm_rawFlags':2097153, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':100, 'm_keyCode':100, 'm_rawFlags':2097153, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed'}, {'m_rawCode':32, 'm_keyCode':32, 'm_rawFlags':3735553, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':32, 'm_keyCode':32, 'm_rawFlags':3735553, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed '}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed '}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed E'}, {'m_rawCode':86, 'm_keyCode':86, 'm_rawFlags':3080193, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':118, 'm_keyCode':118, 'm_rawFlags':3080193, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed Ev'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed Eve'}, {'m_rawCode':78, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':110, 'm_keyCode':110, 'm_rawFlags':3211265, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed Even'}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Renamed Event'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':6, 'm_x':31})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'Sidebar', 'newFocusWindow':(wx.Window,-224), 'lastWidgetValue':u'Renamed Event'}, {'m_x':92, 'm_leftDown':True, 'm_y':126})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'Sidebar', 'newFocusWindow':(wx.Window,-219)}, {'m_x':92, 'm_leftDown':True, 'm_y':126})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':(osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl,-312)}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':78, 'm_shiftDown':True, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':78, 'm_shiftDown':True, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'N'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Ne'}, {'m_rawCode':87, 'm_keyCode':87, 'm_rawFlags':1114113, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':119, 'm_keyCode':119, 'm_rawFlags':1114113, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New'}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New'}, {'m_rawCode':32, 'm_keyCode':32, 'm_rawFlags':3735553, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':32, 'm_keyCode':32, 'm_rawFlags':3735553, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New '}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New '}, {'m_rawCode':67, 'm_shiftDown':True, 'm_keyCode':67, 'm_rawFlags':3014657, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':67, 'm_shiftDown':True, 'm_keyCode':67, 'm_rawFlags':3014657, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New C'}, {'m_rawCode':79, 'm_keyCode':79, 'm_rawFlags':1572865, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':111, 'm_keyCode':111, 'm_rawFlags':1572865, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Co'}, {'m_rawCode':76, 'm_keyCode':76, 'm_rawFlags':2490369, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':108, 'm_keyCode':108, 'm_rawFlags':2490369, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Col'}, {'m_rawCode':76, 'm_keyCode':76, 'm_rawFlags':2490369, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':108, 'm_keyCode':108, 'm_rawFlags':2490369, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Coll'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Colle'}, {'m_rawCode':67, 'm_keyCode':67, 'm_rawFlags':3014657, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':99, 'm_keyCode':99, 'm_rawFlags':3014657, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Collec'}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Collect'}, {'m_rawCode':73, 'm_keyCode':73, 'm_rawFlags':1507329, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':105, 'm_keyCode':105, 'm_rawFlags':1507329, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Collecti'}, {'m_rawCode':79, 'm_keyCode':79, 'm_rawFlags':1572865, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':111, 'm_keyCode':111, 'm_rawFlags':1572865, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Collectio'}, {'m_rawCode':78, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':110, 'm_keyCode':110, 'm_rawFlags':3211265, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Collection'}, {'m_rawCode':9, 'm_keyCode':9, 'm_rawFlags':983041, 'm_y':51, 'm_x':70})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'TimedEvents', 'newFocusWindow':(wx.Window,-219), 'lastWidgetValue':u'New Collection'}, {'m_x':273, 'm_leftDown':True, 'm_y':78})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'TimedEvents', 'newFocusWindow':(wx.Window,-308)}, {'m_x':273, 'm_leftDown':True, 'm_y':78})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'TimedEvents', 'newFocusWindow':(osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor,-309)}, {'m_x':284, 'm_leftDown':True, 'm_y':306})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'TimedEvents', 'newFocusWindow':(wx.Window,-308)}, {'m_x':284, 'm_leftDown':True, 'm_y':306})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'newFocusWindow':(osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor,-309)}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'E'}, {'m_rawCode':86, 'm_keyCode':86, 'm_rawFlags':3080193, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':118, 'm_keyCode':118, 'm_rawFlags':3080193, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Ev'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Eve'}, {'m_rawCode':78, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':110, 'm_keyCode':110, 'm_rawFlags':3211265, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Even'}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Event'}, {'m_rawCode':50, 'm_keyCode':50, 'm_rawFlags':196609, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':50, 'm_keyCode':50, 'm_rawFlags':196609, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Event2'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':-9, 'm_x':26})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':'TimedEvents', 'newFocusWindow':(wx.Window,-308), 'lastWidgetValue':u''}, {'m_x':294, 'm_leftDown':True, 'm_y':108})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':'TimedEvents'}, {'m_x':294, 'm_leftDown':True, 'm_y':108})
    ProcessEvent (wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':'__FocusWindow__', 'selectionRange': (0,9), 'newFocusWindow':(osaf.framework.blocks.calendar.CalendarCanvas.wxInPlaceEditor,-309)}, {'m_x':36, 'm_y':14})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':16, 'm_shiftDown':True, 'm_keyCode':306, 'm_rawFlags':3538945, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'New Event'}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':69, 'm_shiftDown':True, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'E'}, {'m_rawCode':86, 'm_keyCode':86, 'm_rawFlags':3080193, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':118, 'm_keyCode':118, 'm_rawFlags':3080193, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Ev'}, {'m_rawCode':69, 'm_keyCode':69, 'm_rawFlags':1179649, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':101, 'm_keyCode':101, 'm_rawFlags':1179649, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Eve'}, {'m_rawCode':78, 'm_keyCode':78, 'm_rawFlags':3211265, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':110, 'm_keyCode':110, 'm_rawFlags':3211265, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Even'}, {'m_rawCode':84, 'm_keyCode':84, 'm_rawFlags':1310721, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':116, 'm_keyCode':116, 'm_rawFlags':1310721, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Event'}, {'m_rawCode':49, 'm_keyCode':49, 'm_rawFlags':131073, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':49, 'm_keyCode':49, 'm_rawFlags':131073, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':'__FocusWindow__', 'lastWidgetValue':u'Event1'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':14, 'm_x':36})
    ProcessEvent (wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':'__FocusWindow__'}, {'m_rawCode':13, 'm_keyCode':13, 'm_rawFlags':1835009, 'm_y':14, 'm_x':36})
