import wx, osaf, application
def run():
    """
        Choose menu 'Collection > New' (0)
        Type u'New' (4)
        Left Mouse Down in ApplicationBar (16)
        Left Mouse Down in ApplicationBar (18)
        Choose toolbar button 'New' (20)
        Type u'all view' (23)
        Left Mouse Down in ApplicationBar (46)
        Choose toolbar button 'Mail' (48)
        Left Mouse Down in ApplicationBar (50)
        Choose toolbar button 'New' (52)
        Type u'mail view' (55)
        Left Mouse Down in ApplicationBar (81)
        Choose toolbar button 'Calendar' (83)
        Left Mouse Down in ApplicationBar (85)
        Choose toolbar button 'New' (87)
        Left Mouse Down in HeadlineBlockAEStaticControl (88)
        Choose menu 'Edit > Select All' (91)
        Type u'calenc\x08dar view' (93)
        Left Mouse Down in ApplicationBar (137)
        Choose toolbar button 'All' (139)
        Left Mouse Down in DashboardSummaryViewColLabelWindow (141)
        Left Mouse Down in DashboardSummaryViewGridWindow (143)
        Left Mouse Down in DashboardSummaryViewGridWindow (145)
        Left Mouse Double Click in DashboardSummaryViewGridWindow
        Left Mouse Down in DashboardSummaryViewAttributeEditor (150)
        Type u'v' (153)
        Left Mouse Down in DashboardSummaryViewGridWindow (158)
        Left Mouse Double Click in DashboardSummaryViewGridWindow
        Left Mouse Down in DashboardSummaryViewAttributeEditor (163)
        Type u'v' (166)
        Left Mouse Down in DashboardSummaryViewGridWindow (171)
        Left Mouse Double Click in DashboardSummaryViewGridWindow
        Left Mouse Down in DashboardSummaryViewAttributeEditor (176)
        Type u'v' (179)
    """

    wx.GetApp().RunRecordedScript ([
        (0, wx.CommandEvent, {'associatedBlock':'NewCollectionItem', 'eventType':wx.EVT_MENU, 'sentTo':u'MainViewRoot'}, {}),
        (1, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'SidebarAttributeEditor'}, {}),
        (2, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':16, 'm_keyCode':306, 'm_shiftDown':True, 'm_x':124, 'm_y':-187, 'UnicodeKey':16}),
        (3, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':78, 'm_keyCode':78, 'm_shiftDown':True, 'm_x':124, 'm_y':-187, 'UnicodeKey':78}),
        (4, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':78, 'm_keyCode':78, 'm_shiftDown':True, 'm_x':124, 'm_y':-187, 'UnicodeKey':78}),
        (5, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'SidebarAttributeEditor'}, {'m_rawCode':78, 'm_keyCode':78, 'm_shiftDown':True, 'm_x':124, 'm_y':-187, 'UnicodeKey':78}),
        (6, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'SidebarAttributeEditor'}, {'m_rawCode':16, 'm_keyCode':306, 'm_x':124, 'm_y':-187, 'UnicodeKey':16}),
        (7, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'N'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':124, 'm_y':-187, 'UnicodeKey':69}),
        (8, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'N'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':124, 'm_y':-187, 'UnicodeKey':101}),
        (9, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'Ne'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':124, 'm_y':-187, 'UnicodeKey':87}),
        (10, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'Ne'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':124, 'm_y':-187, 'UnicodeKey':119}),
        (11, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'SidebarAttributeEditor'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':124, 'm_y':-187, 'UnicodeKey':69}),
        (12, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'SidebarAttributeEditor'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':124, 'm_y':-187, 'UnicodeKey':87}),
        (13, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'SidebarAttributeEditor', 'lastWidgetValue':u'New'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':-12, 'm_y':-157, 'UnicodeKey':13}),
        (14, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'SidebarGridWindow'}, {}),
        (15, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'SidebarGridWindow'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':10, 'm_y':-25, 'UnicodeKey':13}),
        (16, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'recordedFocusWindow':u'SidebarGridWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':11, 'm_y':33}),
        (17, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':11, 'm_y':33}),
        (18, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar'}, {'m_leftDown':True, 'm_x':286, 'm_y':31}),
        (19, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':286, 'm_y':31}),
        (20, wx.CommandEvent, {'associatedBlock':'ApplicationBarNewButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (21, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (22, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-407, 'm_y':-87, 'UnicodeKey':65}),
        (23, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'Untitled'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-407, 'm_y':-87, 'UnicodeKey':97}),
        (24, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-407, 'm_y':-87, 'UnicodeKey':65}),
        (25, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'a'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-407, 'm_y':-87, 'UnicodeKey':76}),
        (26, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'a'}, {'m_rawCode':108, 'm_keyCode':108, 'm_x':-407, 'm_y':-87, 'UnicodeKey':108}),
        (27, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-407, 'm_y':-87, 'UnicodeKey':76}),
        (28, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'al'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-407, 'm_y':-87, 'UnicodeKey':76}),
        (29, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'al'}, {'m_rawCode':108, 'm_keyCode':108, 'm_x':-407, 'm_y':-87, 'UnicodeKey':108}),
        (30, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-407, 'm_y':-87, 'UnicodeKey':76}),
        (31, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-407, 'm_y':-87, 'UnicodeKey':32}),
        (32, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-407, 'm_y':-87, 'UnicodeKey':32}),
        (33, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-407, 'm_y':-87, 'UnicodeKey':32}),
        (34, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all '}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-407, 'm_y':-87, 'UnicodeKey':86}),
        (35, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all '}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':-407, 'm_y':-87, 'UnicodeKey':118}),
        (36, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-407, 'm_y':-87, 'UnicodeKey':86}),
        (37, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all v'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-407, 'm_y':-87, 'UnicodeKey':73}),
        (38, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all v'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':-407, 'm_y':-87, 'UnicodeKey':105}),
        (39, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-407, 'm_y':-87, 'UnicodeKey':73}),
        (40, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all vi'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-407, 'm_y':-87, 'UnicodeKey':69}),
        (41, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all vi'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-407, 'm_y':-87, 'UnicodeKey':101}),
        (42, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all vie'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-407, 'm_y':-87, 'UnicodeKey':87}),
        (43, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'all vie'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':-407, 'm_y':-87, 'UnicodeKey':119}),
        (44, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-407, 'm_y':-87, 'UnicodeKey':69}),
        (45, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-407, 'm_y':-87, 'UnicodeKey':87}),
        (46, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'lastWidgetValue':u'all view'}, {'m_leftDown':True, 'm_x':65, 'm_y':24}),
        (47, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':66, 'm_y':24}),
        (48, wx.CommandEvent, {'associatedBlock':'ApplicationBarMailButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (49, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (50, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'recordedFocusWindow':u'DashboardSummaryViewGridWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':277, 'm_y':17}),
        (51, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':277, 'm_y':17}),
        (52, wx.CommandEvent, {'associatedBlock':'ApplicationBarNewButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (53, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (54, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'Untitled'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':-416, 'm_y':-201, 'UnicodeKey':77}),
        (55, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'Untitled'}, {'m_rawCode':109, 'm_keyCode':109, 'm_x':-416, 'm_y':-201, 'UnicodeKey':109}),
        (56, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':77, 'm_keyCode':77, 'm_x':-416, 'm_y':-201, 'UnicodeKey':77}),
        (57, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'm'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-416, 'm_y':-201, 'UnicodeKey':65}),
        (58, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'm'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-416, 'm_y':-201, 'UnicodeKey':97}),
        (59, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ma'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-416, 'm_y':-201, 'UnicodeKey':73}),
        (60, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ma'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':-416, 'm_y':-201, 'UnicodeKey':105}),
        (61, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mai'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-416, 'm_y':-201, 'UnicodeKey':76}),
        (62, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mai'}, {'m_rawCode':108, 'm_keyCode':108, 'm_x':-416, 'm_y':-201, 'UnicodeKey':108}),
        (63, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-416, 'm_y':-201, 'UnicodeKey':65}),
        (64, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-416, 'm_y':-201, 'UnicodeKey':73}),
        (65, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-416, 'm_y':-201, 'UnicodeKey':76}),
        (66, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-416, 'm_y':-201, 'UnicodeKey':32}),
        (67, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-416, 'm_y':-201, 'UnicodeKey':32}),
        (68, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-416, 'm_y':-201, 'UnicodeKey':32}),
        (69, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail '}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-416, 'm_y':-201, 'UnicodeKey':86}),
        (70, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail '}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':-416, 'm_y':-201, 'UnicodeKey':118}),
        (71, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-416, 'm_y':-201, 'UnicodeKey':86}),
        (72, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail v'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-416, 'm_y':-201, 'UnicodeKey':73}),
        (73, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail v'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':-416, 'm_y':-201, 'UnicodeKey':105}),
        (74, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-416, 'm_y':-201, 'UnicodeKey':73}),
        (75, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail vi'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-416, 'm_y':-201, 'UnicodeKey':69}),
        (76, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail vi'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-416, 'm_y':-201, 'UnicodeKey':101}),
        (77, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail vie'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-416, 'm_y':-201, 'UnicodeKey':87}),
        (78, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'mail vie'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':-416, 'm_y':-201, 'UnicodeKey':119}),
        (79, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-416, 'm_y':-201, 'UnicodeKey':69}),
        (80, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-416, 'm_y':-201, 'UnicodeKey':87}),
        (81, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'lastWidgetValue':u'mail view'}, {'m_leftDown':True, 'm_x':173, 'm_y':15}),
        (82, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':173, 'm_y':15}),
        (83, wx.CommandEvent, {'associatedBlock':'ApplicationBarEventButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (84, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'TimedEventsFocusWindow'}, {}),
        (85, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'recordedFocusWindow':u'TimedEventsFocusWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':271, 'm_y':23}),
        (86, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':271, 'm_y':23}),
        (87, wx.CommandEvent, {'associatedBlock':'ApplicationBarNewButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (88, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'HeadlineBlockAEStaticControl'}, {'m_leftDown':True, 'm_x':49, 'm_y':5}),
        (89, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'HeadlineBlockAEStaticControl'}, {'m_x':49, 'm_y':5}),
        (90, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'HeadlineBlockAEEditControl'}, {}),
        (91, wx.CommandEvent, {'associatedBlock':'SelectAllItem', 'eventType':wx.EVT_MENU, 'sentTo':u'MainViewRoot', 'lastWidgetValue':u'New Event'}, {}),
        (92, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':67, 'm_keyCode':67, 'm_x':-590, 'm_y':-20, 'UnicodeKey':67}),
        (93, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'recordedFocusWindow':u'HeadlineBlockAEEditControl', 'recordedFocusWindowClass':osaf.framework.attributeEditors.DragAndDropTextCtrl.DragAndDropTextCtrl, 'lastWidgetValue':u'New Event'}, {'m_rawCode':99, 'm_keyCode':99, 'm_x':-590, 'm_y':-20, 'UnicodeKey':99}),
        (94, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':67, 'm_keyCode':67, 'm_x':-590, 'm_y':-20, 'UnicodeKey':67}),
        (95, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'c'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-590, 'm_y':-20, 'UnicodeKey':65}),
        (96, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'c'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-590, 'm_y':-20, 'UnicodeKey':97}),
        (97, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ca'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-590, 'm_y':-20, 'UnicodeKey':76}),
        (98, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'ca'}, {'m_rawCode':108, 'm_keyCode':108, 'm_x':-590, 'm_y':-20, 'UnicodeKey':108}),
        (99, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-590, 'm_y':-20, 'UnicodeKey':65}),
        (100, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':76, 'm_keyCode':76, 'm_x':-590, 'm_y':-20, 'UnicodeKey':76}),
        (101, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'cal'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-590, 'm_y':-20, 'UnicodeKey':69}),
        (102, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'cal'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-590, 'm_y':-20, 'UnicodeKey':101}),
        (103, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'cale'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':-590, 'm_y':-20, 'UnicodeKey':78}),
        (104, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'cale'}, {'m_rawCode':110, 'm_keyCode':110, 'm_x':-590, 'm_y':-20, 'UnicodeKey':110}),
        (105, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-590, 'm_y':-20, 'UnicodeKey':69}),
        (106, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':78, 'm_keyCode':78, 'm_x':-590, 'm_y':-20, 'UnicodeKey':78}),
        (107, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calen'}, {'m_rawCode':67, 'm_keyCode':67, 'm_x':-590, 'm_y':-20, 'UnicodeKey':67}),
        (108, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calen'}, {'m_rawCode':99, 'm_keyCode':99, 'm_x':-590, 'm_y':-20, 'UnicodeKey':99}),
        (109, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':67, 'm_keyCode':67, 'm_x':-590, 'm_y':-20, 'UnicodeKey':67}),
        (110, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calenc'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':-590, 'm_y':-20, 'UnicodeKey':8}),
        (111, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calenc'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':-590, 'm_y':-20, 'UnicodeKey':8}),
        (112, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':8, 'm_keyCode':8, 'm_x':-590, 'm_y':-20, 'UnicodeKey':8}),
        (113, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calen'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':-590, 'm_y':-20, 'UnicodeKey':68}),
        (114, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calen'}, {'m_rawCode':100, 'm_keyCode':100, 'm_x':-590, 'm_y':-20, 'UnicodeKey':100}),
        (115, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':68, 'm_keyCode':68, 'm_x':-590, 'm_y':-20, 'UnicodeKey':68}),
        (116, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calend'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-590, 'm_y':-20, 'UnicodeKey':65}),
        (117, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calend'}, {'m_rawCode':97, 'm_keyCode':97, 'm_x':-590, 'm_y':-20, 'UnicodeKey':97}),
        (118, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calenda'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':-590, 'm_y':-20, 'UnicodeKey':82}),
        (119, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calenda'}, {'m_rawCode':114, 'm_keyCode':114, 'm_x':-590, 'm_y':-20, 'UnicodeKey':114}),
        (120, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':65, 'm_keyCode':65, 'm_x':-590, 'm_y':-20, 'UnicodeKey':65}),
        (121, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':82, 'm_keyCode':82, 'm_x':-590, 'm_y':-20, 'UnicodeKey':82}),
        (122, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-590, 'm_y':-20, 'UnicodeKey':32}),
        (123, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-590, 'm_y':-20, 'UnicodeKey':32}),
        (124, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':32, 'm_keyCode':32, 'm_x':-590, 'm_y':-20, 'UnicodeKey':32}),
        (125, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar '}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-590, 'm_y':-20, 'UnicodeKey':86}),
        (126, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar '}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':-590, 'm_y':-20, 'UnicodeKey':118}),
        (127, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':-590, 'm_y':-20, 'UnicodeKey':86}),
        (128, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar v'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-590, 'm_y':-20, 'UnicodeKey':73}),
        (129, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar v'}, {'m_rawCode':105, 'm_keyCode':105, 'm_x':-590, 'm_y':-20, 'UnicodeKey':105}),
        (130, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':73, 'm_keyCode':73, 'm_x':-590, 'm_y':-20, 'UnicodeKey':73}),
        (131, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar vi'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-590, 'm_y':-20, 'UnicodeKey':69}),
        (132, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar vi'}, {'m_rawCode':101, 'm_keyCode':101, 'm_x':-590, 'm_y':-20, 'UnicodeKey':101}),
        (133, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar vie'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-590, 'm_y':-20, 'UnicodeKey':87}),
        (134, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'HeadlineBlockAEEditControl', 'lastWidgetValue':u'calendar vie'}, {'m_rawCode':119, 'm_keyCode':119, 'm_x':-590, 'm_y':-20, 'UnicodeKey':119}),
        (135, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':69, 'm_keyCode':69, 'm_x':-590, 'm_y':-20, 'UnicodeKey':69}),
        (136, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'HeadlineBlockAEEditControl'}, {'m_rawCode':87, 'm_keyCode':87, 'm_x':-590, 'm_y':-20, 'UnicodeKey':87}),
        (137, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'ApplicationBar', 'lastWidgetValue':u'calendar view'}, {'m_leftDown':True, 'm_x':25, 'm_y':29}),
        (138, wx.MouseEvent, {'associatedBlock':'ApplicationBar', 'eventType':wx.EVT_LEFT_UP, 'sentTo':u'ApplicationBar'}, {'m_x':25, 'm_y':29}),
        (139, wx.CommandEvent, {'associatedBlock':'ApplicationBarAllButton', 'eventType':wx.EVT_MENU, 'sentTo':u'ApplicationBar'}, {}),
        (140, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (141, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewColLabelWindow', 'recordedFocusWindow':u'DashboardSummaryViewGridWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':176, 'm_y':11}),
        (142, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewColLabelWindow'}, {'m_x':176, 'm_y':11}),
        (143, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_leftDown':True, 'm_x':201, 'm_y':11}),
        (144, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_x':201, 'm_y':11}),
        (145, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_leftDown':True, 'm_x':194, 'm_y':11}),
        (146, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_x':194, 'm_y':11}),
        (147, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_leftDown':True, 'm_x':194, 'm_y':11}),
        (148, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {}),
        (149, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (0,8)}, {'m_x':38, 'm_y':9}),
        (150, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindow':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u'all view'}, {'m_leftDown':True, 'm_x':43, 'm_y':7}),
        (151, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (8,8)}, {'m_x':44, 'm_y':7}),
        (152, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'all view'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':47, 'm_y':8, 'UnicodeKey':86}),
        (153, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'all view'}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':47, 'm_y':8, 'UnicodeKey':118}),
        (154, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':47, 'm_y':8, 'UnicodeKey':86}),
        (155, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'all viewv'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':47, 'm_y':8, 'UnicodeKey':13}),
        (156, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (157, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':201, 'm_y':8, 'UnicodeKey':13}),
        (158, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewGridWindow', 'recordedFocusWindow':u'DashboardSummaryViewGridWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':219, 'm_y':25}),
        (159, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_x':219, 'm_y':25}),
        (160, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_leftDown':True, 'm_x':219, 'm_y':25}),
        (161, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {}),
        (162, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (0,13)}, {'m_x':63, 'm_y':5}),
        (163, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindow':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u'calendar view'}, {'m_leftDown':True, 'm_x':109, 'm_y':11}),
        (164, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (13,13)}, {'m_x':109, 'm_y':11}),
        (165, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'calendar view'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':111, 'm_y':13, 'UnicodeKey':86}),
        (166, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'calendar view'}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':111, 'm_y':13, 'UnicodeKey':118}),
        (167, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':111, 'm_y':13, 'UnicodeKey':86}),
        (168, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'calendar viewv'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':111, 'm_y':13, 'UnicodeKey':13}),
        (169, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (170, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':265, 'm_y':31, 'UnicodeKey':13}),
        (171, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewGridWindow', 'recordedFocusWindow':u'DashboardSummaryViewGridWindow', 'recordedFocusWindowClass':wx.Window}, {'m_leftDown':True, 'm_x':245, 'm_y':44}),
        (172, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_x':245, 'm_y':44}),
        (173, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DCLICK, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_leftDown':True, 'm_x':245, 'm_y':44}),
        (174, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {}),
        (175, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (0,9)}, {'m_x':89, 'm_y':5}),
        (176, wx.MouseEvent, {'eventType':wx.EVT_LEFT_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindow':u'DashboardSummaryViewAttributeEditor', 'recordedFocusWindowClass':osaf.framework.attributeEditors.AETypeOverTextCtrl.AENonTypeOverTextCtrl, 'lastWidgetValue':u'mail view'}, {'m_leftDown':True, 'm_x':80, 'm_y':6}),
        (177, wx.MouseEvent, {'eventType':wx.EVT_LEFT_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'selectionRange': (9,9)}, {'m_x':80, 'm_y':6}),
        (178, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'mail view'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':82, 'm_y':8, 'UnicodeKey':86}),
        (179, wx.KeyEvent, {'eventType':wx.EVT_CHAR, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'mail view'}, {'m_rawCode':118, 'm_keyCode':118, 'm_x':82, 'm_y':8, 'UnicodeKey':118}),
        (180, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewAttributeEditor'}, {'m_rawCode':86, 'm_keyCode':86, 'm_x':82, 'm_y':8, 'UnicodeKey':86}),
        (181, wx.KeyEvent, {'eventType':wx.EVT_KEY_DOWN, 'sentTo':u'DashboardSummaryViewAttributeEditor', 'lastWidgetValue':u'mail viewv'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':82, 'm_y':8, 'UnicodeKey':13}),
        (182, wx.FocusEvent, {'eventType':wx.EVT_SET_FOCUS, 'sentTo':u'DashboardSummaryViewGridWindow'}, {}),
        (183, wx.KeyEvent, {'eventType':wx.EVT_KEY_UP, 'sentTo':u'DashboardSummaryViewGridWindow'}, {'m_rawCode':13, 'm_keyCode':13, 'm_x':236, 'm_y':45, 'UnicodeKey':13}),
    ])
