mv ${DSTDIR}/chandler/mac/release/icu/lib/libicudata.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicudata.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libicui18n.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicui18n.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libicuio.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicuio.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libicule.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicule.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libiculx.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libiculx.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libicutu.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicutu.dylib.36
mv ${DSTDIR}/chandler/mac/release/icu/lib/libicuuc.dylib.36.0 ${DSTDIR}/chandler/mac/release/icu/lib/libicuuc.dylib.36
mv ${DSTDIR}/chandler/mac/release/lib/libwx_macu-2.8.0.1.1.dylib ${DSTDIR}/chandler/mac/release/lib/libwx_macu-2.8.0.dylib
mv ${DSTDIR}/chandler/mac/release/lib/libwx_macu_gizmos-2.8.0.1.0.dylib ${DSTDIR}/chandler/mac/release/lib/libwx_macu_gizmos-2.8.0.dylib
mv ${DSTDIR}/chandler/mac/release/lib/libwx_macu_gizmos_xrc-2.8.0.1.0.dylib ${DSTDIR}/chandler/mac/release/lib/libwx_macu_gizmos_xrc-2.8.0.dylib
mv ${DSTDIR}/chandler/mac/release/lib/libwx_macu_stc-2.8.0.1.0.dylib ${DSTDIR}/chandler/mac/release/lib/libwx_macu_stc-2.8.0.dylib
mv ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u-2.8.so.0.1.1 ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u-2.8.so.0
mv ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_gizmos-2.8.so.0.1.0 ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_gizmos-2.8.so.0
mv ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_gizmos_xrc-2.8.so.0.1.0 ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_gizmos_xrc-2.8.so.0
mv ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_stc-2.8.so.0.1.0 ${DSTDIR}/chandler/linux/release/lib/libwx_gtk2u_stc-2.8.so.0
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicudata.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicudata.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicui18n.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicui18n.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicuio.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicuio.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicule.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicule.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libiculx.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libiculx.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicutu.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicutu.so.36
mv ${DSTDIR}/chandler/linux/release/icu/lib/libicuuc.so.36.0 ${DSTDIR}/chandler/linux/release/icu/lib/libicuuc.so.36
