
# An OS X Makefile for development only

ifeq ($(DEBUG),1)

CCFLAGS = -O -g
LDFLAGS = -g
mode = debug

else

CCFLAGS = -O2 -g
LDFLAGS = -g
mode = release

endif

SRCDIR = .
BINDIR = build_$(mode)

CLASSES = $(BINDIR)/classes
CC = $(GCJ_HOME)/bin/gcc
CXX = $(GCJ_HOME)/bin/g++
JCC = $(GCJ_HOME)/bin/gcj
JCCH = $(GCJ_HOME)/bin/gcjh

LUCENE = $(SRCDIR)/lucene
DB = $(SRCDIR)/../db
PYTHON = /Library/Frameworks/Python.framework/Versions/2.3

PYTHON_INC = $(PYTHON)/include/python2.3
PYTHON_SITE = $(PYTHON)/lib/python2.3/site-packages

LUCENE_SRCS = `find $(LUCENE)/src/java -name '*.java' -print`
DB_SRCS = `find $(DB)/java/src/com/sleepycat/db -regex '.*/db/[^/]*java'`
STORE_SRCS = `find store -name '*.java' -print`

OBJS = $(BINDIR)/store.o $(BINDIR)/db_const.o $(BINDIR)/db.o $(BINDIR)/lucene.o $(BINDIR)/reader.java.o $(BINDIR)/reader.cpp.o


$(BINDIR)/lucene.o:
	if [ ! -d $(BINDIR) ]; then mkdir -p $(BINDIR)/classes; fi
	$(JCC) -C -d $(CLASSES) $(LUCENE_SRCS)
	$(JCC) $(CCFLAGS) -c -o $(BINDIR)/lucene.o $(LUCENE_SRCS)

$(BINDIR)/db_const.o:
	if [ ! -d $(BINDIR) ]; then mkdir -p $(BINDIR)/classes; fi
	$(JCC) -C -d $(CLASSES) $(DB)/java/src/com/sleepycat/db/$(mode)/DbConstants.java
	$(JCC) -fjni $(CCFLAGS) -c -o $(BINDIR)/db_const.o $(DB)/java/src/com/sleepycat/db/$(mode)/DbConstants.java

$(BINDIR)/db.o: $(BINDIR)/db_const.o
	$(JCC) -C -d $(CLASSES) --classpath=$(CLASSES) $(DB_SRCS)
	$(JCC) -fjni $(CCFLAGS) -c -o $(BINDIR)/db.o --classpath=$(CLASSES) $(DB_SRCS)

$(BINDIR)/libdb_java-4.2.jnilib:
	$(CC) -shared -bundle -o $(BINDIR)/libdb_java-4.2.jnilib -O $(LDFLAGS) -I$(DB) -I$(DB)/build_$(mode) -I/usr/local/BerkeleyDB.4.2/include $(DB)/libdb_java/db_java_wrap.c ../../$(mode)/db/lib/libdb-4.2.dylib

$(BINDIR)/store.o: $(BINDIR)/db.o $(BINDIR)/lucene.o
	$(JCC) -C -d $(CLASSES) --classpath=$(CLASSES) $(STORE_SRCS)
	$(JCC) -fjni $(CCFLAGS) -c -o $(BINDIR)/store.o --classpath=$(CLASSES) $(STORE_SRCS)

$(BINDIR)/reader.java.o: java/org/osafoundation/io/PythonReader.java
	$(JCC) -C -d $(CLASSES) java/org/osafoundation/io/PythonReader.java
	$(JCC) $(CCFLAGS) -c -o $(BINDIR)/reader.java.o java/org/osafoundation/io/PythonReader.java

$(BINDIR)/reader.cpp.o: cpp/PythonReader.cpp $(BINDIR)/reader.java.o
	$(JCC) -I$(PYTHON_INC) -I$(CLASSES) $(CCFLAGS) -c -o $(BINDIR)/reader.cpp.o cpp/PythonReader.cpp

PyLucene_wrap.cxx: PyLucene.i $(BINDIR)/reader.java.o
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) com.sleepycat.db.DbEnv
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) com.sleepycat.db.Db
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) com.sleepycat.db.DbTxn
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.store.Directory
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.store.db.DbDirectory
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.analysis.Analyzer
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.analysis.standard.StandardAnalyzer
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.document.Field
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.document.Document
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.index.IndexWriter
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.search.Searcher
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.search.Query
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.search.Hits
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.search.IndexSearcher
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.apache.lucene.queryParser.QueryParser
	$(JCCH) -d $(CLASSES) --classpath=$(CLASSES) org.osafoundation.io.PythonReader
	swig -modern -I$(BINDIR)/classes -c++ -python PyLucene.i

$(BINDIR)/_PyLucene.so: $(OBJS) PyLucene_wrap.cxx
	$(CXX) -shared -bundle -o $(BINDIR)/_PyLucene.so $(CCFLAGS) -I$(CLASSES) -I$(PYTHON_INC) -I/usr/local/BerkeleyDB.4.2/include PyLucene_wrap.cxx $(BINDIR)/db_const.o $(BINDIR)/db.o $(BINDIR)/store.o $(BINDIR)/lucene.o $(BINDIR)/reader.java.o $(BINDIR)/reader.cpp.o -lgcj -liconv -flat_namespace -multiply_defined suppress -undefined warning

all: $(BINDIR)/_PyLucene.so $(BINDIR)/libdb_java-4.2.jnilib
	echo build of $(BINDIR)/_PyLucene.so complete

install: $(BINDIR)/_PyLucene.so $(BINDIR)/libdb_java-4.2.jnilib
	install PyLucene.py $(PYTHON_SITE)
	install $(BINDIR)/_PyLucene.so $(PYTHON_SITE)
	install $(BINDIR)/libdb_java-4.2.jnilib /usr/local/BerkeleyDB.4.2/lib
	install libdb_java-4.2.la.osx /usr/local/BerkeleyDB.4.2/lib/libdb_java-4.2.la

clean:
	rm -f PyLucene_wrap.cxx
	rm -rf build_$(mode)
