
from detailblocks import installParcel

from Detail import (
    AttachmentAreaBlock, 
    AttachmentTextFieldBlock, 
    AcceptShareButtonBlock,
    CalendarAllDayAreaBlock,
    CalendarAtLabelBlock,
    CalendarLocationAreaBlock, 
    CalendarRecurrenceCustomAreaBlock, 
    CalendarRecurrenceEndAreaBlock, 
    CalendarRecurrencePopupAreaBlock, 
    CalendarRecurrenceSpacer2Area, 
    CalendarReminderAreaBlock, 
    CalendarStampBlock,
    CalendarTimeAEBlock,
    CalendarTimeZoneAreaBlock,
    DetailRootBlock, 
    DetailSynchronizedAttributeEditorBlock,
    DetailSynchronizedContentItemDetail,
    DetailSynchronizedLabeledTextAttributeBlock, 
    DetailTrunkDelegate, 
    DetailTrunkSubtree, 
    EditSharingActiveBlock, 
    EmptyPanelBlock,
    HTMLDetailArea,
    InviteEditFieldBlock, 
    LabeledTextAttributeBlock, 
    MailMessageButtonBlock,
    MarkupBarBlock, 
    ParticipantsTextFieldBlock, 
    PrivateSwitchButtonBlock, 
    SharingArea, 
    StaticRedirectAttribute,
    StaticRedirectAttributeLabel, 
    StaticTextLabel, 
    TaskStampBlock
)
    