#!/bin/sh

unset DYLD_LIBRARY_PATH DYLD_FRAMEWORK_PATH
unset PYTHONHOME PYTHONBIN PYTHON_VER
unset CHANDLERHOME CHANDLERBIN

cd "$(dirname "${0}")"
execdir="$PWD"
resdir="$(dirname "${execdir}")/Resources"
exec "${resdir}/release/RunChandler"
