## This file reverse renames symbols in the wx package to give
## them their wx prefix again, for backwards compatibility.
##
## Generated by BuildRenamers in config.py

# This silly stuff here is so the wxPython.wx module doesn't conflict
# with the wx package.  We need to import modules from the wx package
# here, then we'll put the wxPython.wx entry back in sys.modules.
import sys
_wx = None
if sys.modules.has_key('wxPython.wx'):
    _wx = sys.modules['wxPython.wx']
    del sys.modules['wxPython.wx']

import wx.minical

sys.modules['wxPython.wx'] = _wx
del sys, _wx


# Now assign all the reverse-renamed names:
wxCAL_SUNDAY_FIRST = wx.minical.CAL_SUNDAY_FIRST
wxCAL_MONDAY_FIRST = wx.minical.CAL_MONDAY_FIRST
wxCAL_SHOW_SURROUNDING_WEEKS = wx.minical.CAL_SHOW_SURROUNDING_WEEKS
wxCAL_SHOW_PREVIEW = wx.minical.CAL_SHOW_PREVIEW
wxCAL_HITTEST_NOWHERE = wx.minical.CAL_HITTEST_NOWHERE
wxCAL_HITTEST_HEADER = wx.minical.CAL_HITTEST_HEADER
wxCAL_HITTEST_DAY = wx.minical.CAL_HITTEST_DAY
wxCAL_HITTEST_TODAY = wx.minical.CAL_HITTEST_TODAY
wxCAL_HITTEST_INCMONTH = wx.minical.CAL_HITTEST_INCMONTH
wxCAL_HITTEST_DECMONTH = wx.minical.CAL_HITTEST_DECMONTH
wxCAL_HITTEST_SURROUNDING_WEEK = wx.minical.CAL_HITTEST_SURROUNDING_WEEK
wxMiniCalendarDateAttr = wx.minical.MiniCalendarDateAttr
wxMiniCalendarDateAttrPtr = wx.minical.MiniCalendarDateAttrPtr
wxMiniCalendarEvent = wx.minical.MiniCalendarEvent
wxMiniCalendarEventPtr = wx.minical.MiniCalendarEventPtr
wxEVT_MINI_CALENDAR_DOUBLECLICKED = wx.minical.wxEVT_MINI_CALENDAR_DOUBLECLICKED
wxEVT_MINI_CALENDAR_SEL_CHANGED = wx.minical.wxEVT_MINI_CALENDAR_SEL_CHANGED
wxEVT_MINI_CALENDAR_DAY_CHANGED = wx.minical.wxEVT_MINI_CALENDAR_DAY_CHANGED
wxEVT_MINI_CALENDAR_MONTH_CHANGED = wx.minical.wxEVT_MINI_CALENDAR_MONTH_CHANGED
wxEVT_MINI_CALENDAR_YEAR_CHANGED = wx.minical.wxEVT_MINI_CALENDAR_YEAR_CHANGED
wxMiniCalendar = wx.minical.MiniCalendar
wxMiniCalendarPtr = wx.minical.MiniCalendarPtr


