#!/bin/sh

#change here your personnal path to Chandler
CHANDLERHOME=/Users/olivier/chandler
#change here your personnal path to CATS
CATSHOME=/Users/olivier/qa/chandler/CATS
#change here your personnal report directory
CATSREPORTDIR=/Users/olivier


if [ "$CHANDLERHOME" = "" ]
then
    CHANDLERHOME=$CHANDLERHOME
fi

if [ "$CATSHOME" = "" ]
then
    CATSHOME=$CATSHOME
fi

if [ "$CATSREPORTDIR" = "" ]
then
    CATSREPORTDIR=$CATSREPORTDIR
fi

export CHANDLERHOME
export CATSHOME
export CATSREPORTDIR

#make CATS libraries available on Chandler
cp -f $CATSHOME/QATestLib/*.py $CHANDLERHOME/parcels/osaf/framework/scripting/
