from osaf.framework.blocks import *
from application import schema
from i18n import OSAFMessageFactory as _
from osaf import messages
from osaf.framework.types.DocumentTypes import ColorType

def makeMainMenus(parcel):
    # in the form 'Color', _('LocalizableColorString'), 360-degree based hue
    collectionHues = [('Blue', _(u'Blue'), 210),
                      ('Green', (u'Green'), 120),
                      ('Rose', _(u'Rose'), 0),
                      ('Salmon', _(u'Salmon'), 30),
                      ('Purple', _(u'Purple'), 270),
                      ('Violet', _(u'Violet'), 240),
                      ('Fuschia', _(u'Fuschia'), 330)]
    
    def makeColorMenuItems (parcel, cls, hues):
        """
        dynamically creates an array of type 'cls' based on a list of colors
        """
        menuItems = []
        
        # make sure that all the events end up in the main parcel
        mainParcel = schema.parcel_for_module ("osaf.views.main", repositoryView)
        for shortName, title, hue in hues:
            rgb = wx.Image.HSVtoRGB (wx.Image_HSVValue (hue/360.0, 0.5, 1.0))
            color = ColorType (rgb.red, rgb.green, rgb.blue, 255)

            colorEvent = ColorEvent.template(
                shortName + 'CollectionColor',
                'SendToBlockByName',
                dispatchToBlockName = 'Sidebar',
                color = color,
                methodName = 'onCollectionColorEvent').install (mainParcel)
    
            menuItem = cls.template(
                shortName + 'ColorItem',
                title = title,
                icon = shortName + "MenuIcon",
                menuItemKind = "Check",
                event = colorEvent)
            menuItems.append (menuItem)

        return menuItems
                                         

    repositoryView = parcel.itsView
    main = schema.ns("osaf.views.main", repositoryView)
    globalBlocks = schema.ns("osaf.framework.blocks", repositoryView)

    MenuBar.template('MenuBar',
        childrenBlocks = [
            Menu.template('FileMenu',
                title = _(u'&File'),
                childrenBlocks = [
                    Menu.template('NewItemMenu',
                        title = _(u'New Item'),
                        helpString = _(u'Create a new Content Item'),
                        childrenBlocks = [
                            MenuItem.template('NewNoteItem',
                                event = main.NewNote,
                                title = _(u'Note'),
                                accel = _(u'Ctrl+N'),
                                helpString = _(u'Create a new Note')),
                            MenuItem.template('NewMessageItem',
                                event = main.NewMailMessage,
                                title = _(u'Message'),
                                accel = _(u'Ctrl+M'),
                                helpString = _(u'Create a new Message')),
                            MenuItem.template('NewTaskItem',
                                event = main.NewTask,
                                title = _(u'Task'),
                                helpString = _(u'Create a new Task')),
                            MenuItem.template('NewEventItem',
                                event = main.NewCalendar,
                                title = _(u'Event'),
                                helpString = _(u'Create a new Event')),
                            MenuItem.template('NewSeparator1',
                                menuItemKind = 'Separator'),
                            MenuItem.template('NewContactItem',
                                title = _(u'Contact'),
                                helpString = _(u'Create a new Contact')),
                            ]), # Menu NewItemMenu
                    MenuItem.template('FileSeparator1',
                        menuItemKind = 'Separator'),
                    MenuItem.template('NewCollectionItem',
                        event = main.NewCollection,
                        title = _(u'New Collection'),
                        helpString = _(u'Create a new Collection')),
                    MenuItem.template('FileSeparator2',
                        menuItemKind = 'Separator'),
                    MenuItem.template('PrintPreviewItem',
                        event = globalBlocks.PrintPreview,
                        title = _(u'Print Preview')),
                    MenuItem.template('PrintItem',
                        event = globalBlocks.Print,
                        title = _(u'Print...'),
                        accel = _(u'Ctrl+P'),
                        helpString = _(u'Print the current calendar')),
                    MenuItem.template('FileSeparator3',
                        menuItemKind = 'Separator'),
                    Menu.template('ImportExportMenu',
                        title = _(u'Import/Export'),
                        childrenBlocks = [
                            MenuItem.template('ImportIcalendarItem',
                                event = main.ImportIcalendar,
                                title = _(u'Import iCalendar data'),
                                helpString = _(u'Import iCalendar file from import.ics')),
                            MenuItem.template('ExportIcalendarItem',
                                event = main.ExportIcalendar,
                                title = _(u'Export Events as iCalendar'),
                                helpString = _(u'Export Calendar Events to export.ics')),
                            MenuItem.template('ImportImageItem',
                                event = main.ImportImage,
                                title = _(u'Import an image from disk'),
                                helpString = _(u'Import an image from disk')),
                            ]), # Menu ImportExportMenu
                    Menu.template('SyncMenu',
                        title = _(u'Sync'),
                        childrenBlocks = [
                            MenuItem.template('SyncAllItem',
                                event = main.SyncAll,
                                title = _(u"Sync All"),
                                helpString = _(u'Sync All')),
                            MenuItem.template('SyncIMAPItem',
                                event = main.GetNewMail,
                                title = _(u'Mail'),
                                helpString = _(u'Sync Mail')),
                            MenuItem.template('SyncWebDAVItem',
                                event = main.SyncWebDAV,
                                title = _(u'Shares'),
                                helpString = _(u'Sync Shares')),
                            ]), # Menu SyncMenu
                    MenuItem.template('PrefsAccountsItem',
                        event = main.EditAccountPreferences,
                        title = _(u'Accounts...'),
                        helpString = messages.ACCOUNT_PREFERENCES),
                    MenuItem.template('FileSeparator4',
                        menuItemKind = 'Separator'),
                    MenuItem.template('QuitItem',
                        event = globalBlocks.Quit,
                        title = _(u'Quit'),
                        accel = _(u'Ctrl+Q'),
                        helpString = _(u'Quit Chandler')),
                    ]), # Menu FileMenu
            Menu.template('EditMenu',
                title = _(u'&Edit'),
                childrenBlocks = [
                    MenuItem.template('UndoItem',
                        event = globalBlocks.Undo,
                        title = messages.UNDO,
                        accel = _(u'Ctrl+Z'),
                        helpString = _(u"Can't Undo")),
                    MenuItem.template('RedoItem',
                        event = globalBlocks.Redo,
                        title = messages.REDO,
                        accel = _(u'Ctrl+Y'),
                        helpString = _(u"Can't Redo")),
                    MenuItem.template('EditSeparator1',
                        menuItemKind = 'Separator'),
                    MenuItem.template('CutItem',
                        event = globalBlocks.Cut,
                        title = messages.CUT,
                        accel = _(u'Ctrl+X')),
                    MenuItem.template('CopyItem',
                        event = globalBlocks.Copy,
                        title = messages.COPY,
                        accel = _(u'Ctrl+C')),
                    MenuItem.template('PasteItem',
                        event = globalBlocks.Paste,
                        title = messages.PASTE,
                        accel = _(u'Ctrl+V')),
                    MenuItem.template('ClearItem',
                        event = globalBlocks.Clear,
                        title = messages.CLEAR),
                    MenuItem.template('SelectAllItem',
                        event = globalBlocks.SelectAll,
                        title = messages.SELECT_ALL,
                        accel = _(u'Ctrl+A'),
                        helpString = _(u'Select all')),
                    MenuItem.template('EditSeparator2',
                        menuItemKind = 'Separator'),
                    MenuItem.template('RemoveItem',
                        event = globalBlocks.Remove,
                        title = _(u'Remove'),
                        helpString = _(u'Remove the current selection from the current collection')),
                    MenuItem.template('DeleteItem',
                        event = main.Delete,
                        title = _(u'Delete'),
                        accel = _(u'Del'),
                        helpString = _(u'Move the current selection to the trash')),
                    MenuItem.template('EmptyTrashItem',
                        event = main.EmptyTrash,
                        title = _(u'Empty Trash'),
                        helpString = _(u'Remove all items from the Trash collection')),
                    ]), # Menu EditMenu
            Menu.template('ViewMenu',
                title = _(u'&View'),
                childrenBlocks = [
                    MenuItem.template('ViewAllItem',
                        event = main.ApplicationBarAll,
                        title = _(u'All items'),
                        menuItemKind = 'Radio',
                        helpString = _(u'View all kinds of items')),
                    MenuItem.template('ViewMailItem',
                        event = main.ApplicationBarMail,
                        title = _(u'Mail'),
                        menuItemKind = 'Radio',
                        helpString = _(u'View only mail messages')),
                    MenuItem.template('ViewTaskItem',
                        event = main.ApplicationBarTask,
                        title = _(u'Tasks'),
                        menuItemKind = 'Radio',
                        helpString = _(u'View only tasks')),
                    MenuItem.template('ViewEventItem',
                        event = main.ApplicationBarEvent,
                        title = _(u'Calendar'),
                        menuItemKind = 'Radio',
                        helpString = _(u'View only calendar items')),
                    MenuItem.template('ViewSeparator1',
                        menuItemKind = 'Separator'),
                    MenuItem.template('ViewToolBarItem',
                        event = main.ShowHideApplicationBar,
                        title = _(u'View Toolbar'),
                        menuItemKind = 'Check',
                        helpString = _(u'Show or Hide the Toolbar')),
                    MenuItem.template('ViewSideBarItem',
                        event = main.ShowHideSidebar,
                        title=_(u'View Sidebar'),
                        menuItemKind='Check',
                        helpString=_(u'Show or hide the Sidebar')),
                    MenuItem.template('ViewStatusBarItem',
                        event = main.ShowHideStatusBar,
                        title=_(u'View Status Bar'),
                        menuItemKind='Check',
                        helpString=_(u'Show or hide the Status bar')),
                    ]), # Menu ViewMenu
            Menu.template('ItemMenu',
                title=_(u'&Item'),
                childrenBlocks=[
                    MenuItem.template('SendMessageItem',
                        event = main.SendShareItem,
                        title=messages.SEND,
                        helpString=_(u'Send the selected Mail Message')),
                    MenuItem.template('ItemSeparator1',
                        menuItemKind='Separator'),
                    MenuItem.template('StampMessageItem',
                        event = main.FocusStampMessage,
                        title=messages.STAMP_MAIL,
                        menuItemKind='Check',
                        helpString=messages.STAMP_MAIL_HELP),
                    MenuItem.template('StampTaskItem',
                        event = main.FocusStampTask,
                        title=messages.STAMP_TASK,
                        menuItemKind='Check',
                        helpString=messages.STAMP_TASK_HELP),
                    MenuItem.template('StampEventItem',
                        event = main.FocusStampCalendar,
                        title=messages.STAMP_CALENDAR,
                        menuItemKind='Check',
                        helpString=messages.STAMP_CALENDAR_HELP),
                    MenuItem.template('ItemSeparator2',
                        menuItemKind='Separator'),
                    MenuItem.template('NeverShareItem',
                        event = main.FocusTogglePrivate,
                        title=messages.PRIVATE,
                        menuItemKind='Check',
                        helpString=_(u'Mark the selected item as private, so it will not be shared')),
                    ]), # Menu ItemMenu
            Menu.template('CollectionMenu',
                title=_(u'&Collection'),
                childrenBlocks=[
                    MenuItem.template('SharingSubscribeToCollectionItem',
                        event = main.SharingSubscribeToCollection,
                        title=_(u'Subscribe...'),
                        helpString=_(u'Subscribe to a published collection')),
                    MenuItem.template('ShareSidebarCollectionItem',
                        event = main.ShareSidebarCollection,
                        title=_(u'Share'),
                        helpString=_(u'Share the selected collection')),
                    MenuItem.template('ManageSidebarCollectionItem',
                        event = main.ManageSidebarCollection,
                        title=_(u'Manage share...'),
                        helpString=_(u'Manage the selected collection')),
                    MenuItem.template('UnsubscribeSidebarCollectionItem',
                        event = main.UnsubscribeSidebarCollection,
                        title=_(u'Unsubscribe'),
                        helpString=_(u'Unsubscribe the selected collection')),
                    MenuItem.template('UnpublishSidebarCollectionItem',
                        event = main.UnpublishSidebarCollection,
                        title=_(u'Unpublish'),
                        helpString=_(u'Remove the collection from the sharing server')),
                    MenuItem.template('CopyCollectionURLItem',
                        event = main.CopyCollectionURL,
                        title=_(u'Copy URL(s) to clipboard'),
                        helpString=_(u"Copy the selected collection's URL(s) to the clipboard")),
                    MenuItem.template('TakeOnlineOfflineItem',
                        event = main.TakeOnlineOffline,
                        title=_(u'Online/Offline status'),
                        helpString=_(u"Toggle the collection's online status")),
                    MenuItem.template('SyncCollectionItem',
                        event = main.SyncCollection,
                        title=_(u'Sync collection'),
                        helpString=_(u'Synchronize a shared collection')),
                    MenuItem.template('RenameItem',
                        event=globalBlocks.Rename,
                        title=_(u'Rename'),
                        helpString=_(u'Rename the selected collection')),
                    Menu.template('CollectionColorMenu',
                        title=_(u'&Collection Color'),
                        childrenBlocks=makeColorMenuItems(parcel,
                                                          MenuItem,
                                                          collectionHues)),
                    MenuItem.template('RestoreSharesItem',
                        event = main.RestoreShares,
                        title=u'Restore published shares...',
                        helpString=u'Restore previously published shares'),
                    MenuItem.template('CollectionSeparator1',
                        menuItemKind='Separator'),
                    MenuItem.template('ToggleMineItem',
                        event = main.ToggleMine,
                        title=_(u'Toggle mine/not-mine'),
                        helpString=_(u'Toggle mine/not-mine')),
                    ]), # Menu CollectionMenu
            Menu.template('TestMenu',
                title=_(u'&Test'),
                childrenBlocks=[
                    MenuItem.template('GenerateSomeDataItem',
                        event = main.GenerateContentItems,
                        title=u'Generate Data',
                        helpString=u'generates a few items of each kind'),
                    MenuItem.template('GenerateMuchDataItem',
                        event = main.GenerateContentItems,
                        title=u'Generate Lots of Data',
                        helpString=u'generates many items of each kind'),
                    MenuItem.template('GenerateDataItemFromFile',
                        event = main.GenerateContentItemsFromFile,
                        title=u'Generate Items from a file',
                        helpString=u'generates Items from a file'),
                    MenuItem.template('MimeTestItem',
                        event = main.MimeTest,
                        title=u'MIME Torture Tests',
                        helpString=u'Loads real world complex / broken mime message examples provided by Anthony Baxter'),
                    MenuItem.template('i18nMailTestItem',
                        event = main.i18nMailTest,
                        title=u'i18n Mail Tests',
                        helpString=u'Loads mail messages containing a variety of Charsets and Languages'),
                    MenuItem.template('StartProfilerItem',
                        event = main.StartProfiler,
                        title=u'Start Profiler',
                        helpString=u'Start profiling events'),
                    MenuItem.template('StopProfilerItem',
                        event = main.StopProfiler,
                        title = u'Stop Profiler',
                        helpString = u'Stop profiling events'),
                    MenuItem.template('ReloadParcelsItem',
                        event = main.ReloadParcels,
                        title = u'Reload Parcels',
                        accel = u'Ctrl+R',
                        helpString = u'Reloads any parcels that have been modified'),
                    MenuItem.template('CommitRepositoryItem',
                        event = main.CommitRepository,
                        title = u'Commit Repository',
                        helpString = u'Performs a repository commit()'),
                    MenuItem.template('CheckRepositoryItem',
                        event = main.CheckRepository,
                        title = u'Check Repository',
                        helpString = u'run check() on the current view'),
                    MenuItem.template('BackupRepositoryItem',
                        event = main.BackupRepository,
                        title = u'Backup Repository',
                        helpString = u'backup the repository'),
                    MenuItem.template('CompactRepositoryItem',
                        event = main.CompactRepository,
                        title = u'Compact Repository',
                        helpString = u'compact the repository'),
                    MenuItem.template('RunSelectedScriptItem',
                        event = main.RunSelectedScript,
                        title = u'Run a Script',
                        accel = u'Ctrl+S',
                        helpString = u'Run the CPIA Script from the Detail View'),
                    MenuItem.template("AddScriptsSetItem",
                        event = main.AddScriptsToSidebar,
                        title = u"Add Scripts to Sidebar",
                        helpString = u'Add Scripts to the Sidebar'),
                    MenuItem.template('WxTestHarnessItem',
                        event = main.WxTestHarness,
                        title = u'Wx Test Harness',
                        helpString = u'invoke the current flavor of wx debugging'),
                    MenuItem.template('ShowPyShellItem',
                        event = main.ShowPyShell,
                        title = u'Show Python shell...',
                        helpString = u'Brings up an interactive Python shell'),
                    MenuItem.template('ShowPyCrustItem',
                        event = main.ShowPyCrust,
                        title = u'Show Python shell with object browser...',
                        helpString = u'Brings up an interactive Python shell and object browser'),
                    MenuItem.template('ShowLogWindowItem',
                        event = main.ShowLogWindow,
                        title = u'Show log window',
                        helpString = u'Displays the contents of chandler.log and twisted.log'),
                    MenuItem.template('ActivateWebserverItem',
                        event = main.ActivateWebserver,
                        title = u'Activate built-in webserver',
                        helpString = u'Activates the built-in webserver at localhost:1888'),
                    MenuItem.template('ActivateShareMergingItem',
                        event = main.ActivateShareMerging,
                        title = u'Activate Share Merging',
                        helpString = u'Activates merging of non-overlapping sharing changes'),
                    MenuItem.template('LoadLoggingConfigItem',
                        event = main.LoadLoggingConfig,
                        title = u'Load logging configuration file...',
                        helpString = u'Load logging configuration file'),
                    MenuItem.template('SearchWindowItem',
                        event = main.SearchWindow,
                        title = u'Search...',
                        helpString = u'PyLucene search'),
                    Menu.template('ShareMenu',
                        title = u'Share',
                        helpString = u'Sharing-related test commands',
                        childrenBlocks = [
                            MenuItem.template('SharingImportDemoCalendarItem',
                                event = main.SharingImportDemoCalendar,
                                title = u'Import demo calendar',
                                helpString = u'Import a demo iCalendar file from osafoundation.org'),
                            MenuItem.template('ShareToolItem',
                                event = main.ShareTool,
                                title = u'Share tool...',
                                helpString = u'Display the Share Tool'),
                            ]), # Menu ShareMenu
                    Menu.template('SkinsMenu',
                        title = u'Skins',
                        helpString = u'Change user-interface skin',
                        childrenBlocks = [
                            MenuItem.template('ChandlerSkinMenuItem',
                                event = main.ChooseChandlerMainView,
                                title = u'Chandler',
                                helpString = u'Switch to Chandler'),
                            MenuItem.template('CPIATestSkinMenuItem',
                                event = main.ChooseCPIATestMainView,
                                title = u'CPIA Test',
                                helpString = u'Switch to CPIA test'),
                            ]), # Menu SkinsMenu
                    Menu.template('AddAdditionalViews',
                        title = u'Add Additional Views',
                        helpString = u'Add views to the sidebar',
                        childrenBlocks = [
                            MenuItem.template('AddAllAdditionalViewsItem',
                                event = main.AddAllAdditionalViews,
                                title = u'Add All Additional Views',
                                helpString = u'Adds all of the extra views to the sidebar'),
                            MenuItem.template('TestSeparator1',
                                menuItemKind = 'Separator'),
                            MenuItem.template('AddRepositoryViewItem',
                                event = main.AddRepositoryView,
                                title = u'Add Repository Viewer',
                                helpString = u'Adds the repository viewer to the sidebar'),
                            MenuItem.template('AddCPIAViewItem',
                                event = main.AddCPIAView,
                                title = u'Add CPIA Viewer',
                                helpString = u'Adds the CPIA viewer to the sidebar'),
                            ]), # Menu AddAdditionalViews
                    MenuItem.template('TestTItem',
                        event = main.Test,
                        title = u'Testing code',
                        helpString = u'Testing code')
                    ]), # Menu TestMenu
            Menu.template('HelpMenu',
                title = _(u'&Help'),
                childrenBlocks = [
                    MenuItem.template('AboutChandlerItem',
                        event = globalBlocks.About,
                        title = _(u'About Chandler'),
                        helpString = _(u'About Chandler...')),
                    ]) # Menu HelpMenu
            ]).install (parcel) # MenuBar MenuBar
