#!/bin/sh
cd ../Chandler
DYLD_LIBRARY_PATH=../debug/lib DYLD_FRAMEWORK_PATH=../debug/bin/Library/Frameworks exec ../debug/bin/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/python Chandler.py
