#!/bin/sh
cd ../Chandler
PYTHONPATH=. PYTHONHOME=../debug/Library/Frameworks/Python.framework/Versions/2.3 DYLD_LIBRARY_PATH=../debug/lib DYLD_FRAMEWORK_PATH=../debug/Library/Frameworks exec ../debug/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python Chandler.py
