#!/bin/sh

if [ "$CHANDLERHOME" = "" ]
then
    CHANDLERHOME=`pwd`
fi

if [ -d $CHANDLERHOME/Chandler -a -f $CHANDLERHOME/debug/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python ]
then
    echo "Using $CHANDLERHOME/debug/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python"
    echo ""
else
    echo "Error:  Please set CHANDLERHOME environment variable to point"
    echo "        to the directory that contains the Chandler and debug"
    echo "        subdirectories, then rerun RunPython"
    exit 1
fi

CHANDLERDIR=$CHANDLERHOME/Chandler PYTHONPATH=$CHANDLERHOME/Chandler PYTHONHOME=$CHANDLERHOME/debug/Library/Frameworks/Python.framework/Versions/2.3 DYLD_LIBRARY_PATH=$CHANDLERHOME/debug/lib:$CHANDLERHOME/debug/dbxml/lib:$CHANDLERHOME/debug/db/lib DYLD_FRAMEWORK_PATH=$CHANDLERHOME/debug/Library/Frameworks exec $CHANDLERHOME/debug/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python $*
