#!/bin/sh

if [ "$CHANDLER_HOME" = "" ]
then
    CHANDLER_HOME=`pwd`
fi

if [ -d $CHANDLER_HOME/Chandler -a -f $CHANDLER_HOME/release/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python ]
then
    echo "Using $CHANDLER_HOME/release/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python"
    echo ""
else
    echo "Error:  Please set CHANDLER_HOME environment variable to point"
    echo "        to the directory that contains the Chandler and release"
    echo "        subdirectories, then rerun RunPython"
    exit 1
fi

PYTHONPATH=$CHANDLER_HOME/Chandler PYTHONHOME=$CHANDLER_HOME/release/Library/Frameworks/Python.framework/Versions/2.3 DYLD_LIBRARY_PATH=$CHANDLER_HOME/release/lib:$CHANDLER_HOME/release/dbxml/lib:$CHANDLER_HOME/release/db/lib DYLD_FRAMEWORK_PATH=$CHANDLER_HOME/release/Library/Frameworks exec $CHANDLER_HOME/release/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/Python -O $*
