#!/bin/sh
cd ../Chandler
DYLD_LIBRARY_PATH=../release/lib DYLD_FRAMEWORK_PATH=../release/Library/Frameworks exec ../release/Library/Frameworks/Python.framework/Versions/2.3/Resources/Python.app/Contents/MacOS/python Chandler.py
